DeveloperAcademy-POSTECH/MC2-Team5-Firefighter

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- close #3 
SnapKit를 추가합니다.
SnapKit 추가했습니다! 얼른 Approved해주세요.
> [ADD] SnapKit 추가

- Manito/Manito/Global/Extension/UIColor+Extension.swift
- close #7 
색상값을 추가했습니다.
* 필요한 색들을 추가했습니다. 혹시나 hex값이 맞지 않거나 필요한 색상이 없는거 같다면 말씀해주세요. 추가해서 반영하겠습니다.
> [ADD] Design Color 추가

- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Extension/UIColor+Extension.swift
- Manito/Manito/Global/Resource/Storyboards/DetailWait.storyboard
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #1 
- BaseViewController를 상속받아 구현했습니다
- 스토리보드 없이 코드베이스로 구현했습니다
- 다른 요소(View)들은 render()에 모아서 위치를 잡고, 선언은 위에서 했는데, 클립보드 복사 토스트는 한 함수에 다 때려박혀있는 느낌이라 이게맞나요?
- 코드가 250줄이 넘는데 어떻게 파일을 분할해야 좋을까요?
- 버튼 실행 함수가 objc func로 되있는데 이게 맞나요?
- 대기중, 진행중, 완료 텍스트를 enum화 하는건 어떤가요?
> [ADD] 대기중 뷰 레이아웃 완료

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Extension/UIView+Extension.swift
- Manito/Manito/Global/UIComponent/MainButton.swift
- Manito/Manito/Screens/Letter/UIComponent/SendLetterView.swift
- close #11 
공통 버튼을 만들고 Letter에다가 적용해뒀습니다.
다른분들도 공통 버튼 변경해주시면 감사드리겠습니다.
공통 버튼에서 바꿀 수 있는 Attribute는 3가지 입니다.
1. Title
2. isDisabled
3. hasShadow
2, 3번은 false가 default라서 두 가지를 false로 설정하고 싶으신 분들은 굳이 손대지 않아도 됩니다.
Title만 설정해주시면 나머지가 알아서 적용됩니다.
* width, height가 잡혀있습니다. top를 설정하고 centerX로 잡아주시면 될 듯 합니다.
* hover 효과를 추가했습니다.
* 혹시 사용법을 모르시겠다면 LetterViewController 코드를 봐주시면 됩니다.!
https://user-images.githubusercontent.com/55099365/173193511-3bd3b90e-3d7b-4076-be86-b042751f9772.mp4
> [ADD] 공통 버튼 추가

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Resource/Storyboards/Splash.storyboard
- Manito/Manito/Global/Supports/Info.plist
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
close #19 
닉네임 생성 뷰 UI 구성입니다. 
- 아직 기능은 연결 안했고 일단 UI 배치만 했습니다. 
- 버튼은 듀나의 Main버튼 컴포넌트 사용했습니다.
> [ADD] 닉네임 생성 뷰 UI 구성완료

- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
close #18
다음 버튼을 듀나 메인버튼으로 재사용
> [CHORE] 다음 버튼 재사용

- .github/auto_assign.yml
- close #22 
Reviewer를 auto로 할 수 없냐길래, 한 번 넣어봤는데 안될 수도 있습니다..^..^
자신의 닉네임(username)이 맞는지 확인부탁드립니다.
> [ADD] auto_assign.yml 파일 생성

- Manito/Manito/Global/Supports/Info.plist
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
close #23 
- 텍스트 필드에 입력받을시 버튼 활성화
- 활성 후 완료 누르면 텍스트 필드 값 변수에 저장 
- 화면에 진입할때 바로 키보드 나오도록 구현
- 저희 컬러에 텍스트필드 플레이스홀더 값에 대한 색(B1B8C0) 이 없었네요. --> 기본색으로 하기로!!
- 다음 기능으로 키보드가 올라오면 버튼 위치 키보드 높이 만큼 올리는거랑 (플레이스홀더 색 변경)이랑 키보드가 나와있을때 화면 아무데나 클릭했을때 키보드 내리는 기능 구현 이슈 파겠습니다.
https://user-images.githubusercontent.com/59243274/173222983-2eb45f20-a164-4006-bc2d-fcaf68300282.mp4
> [FEAT] nickname 생성하는 뷰 기능 구현

- Manito/Manito/Global/Resource/Storyboards/Base.lproj/Main.storyboard
- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Global/Supports/Info.plist
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- close #9 
- 디테일 진행중 UI를 만들었습니다.
- 스토리보드로 레이아웃을 잡았습니다. 
- 마니또 공개하기 버튼만 코드로 레이아웃을 잡았습니다.
- 아직 에셋이 없어서 이미지는 못넣었습니다. background에 색상만 넣어두었습니다.
> [ADD] 디테일 진행중 UI 구현

- Manito/Manito/Global/Base/BaseViewController.swift
- Manito/Manito/Global/Extension/UIViewController+Extension.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
close #26 
- 키보드 on/off에 따라 완료 버튼 위치를 움직이도록 구현했습니다.
- UIViewController 익스텐션에 아무데나 터치해도 키보드가 내려오는 코드를 작성했고 BaseViewController에 넣어놔서 앞으로 그냥 작동할것입니다.
> [FEAT] 닉네임 생성 뷰 키보드 크기 맞춰서 위치 변경

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Extension/UIColor+Extension.swift
- Manito/Manito/Global/Extension/UILabel+Extension.swift
- Manito/Manito/Global/Extension/UIView+Extension.swift
- Manito/Manito/Global/Supports/Info.plist
- Manito/Manito/Network/Models/Letter.swift
- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterHeaderView.swift
- close #13 
쪽지함에 있는 UICollectionViewCell Layout를 구현했습니다.
- 날짜에 해당하는 색상이 없어서 darkGrey005로 추가했습니다.
- 행간을 추가하는 `addLabelSpacing` 메소드를 생성했습니다.
- `makeBorderLayer` 메소드를 UIView+Extension에 추가했습니다. 인자로 원하는 Color만 넣으면 Border cornerRadius와 색상, width를 잡아줍니다.
- 더미 데이터가 필요해서 Letter Struct를 만들었습니다. 
- 사진, 하단 텍스트가 있을 수도 없을 수도 있어서 그 부분을 StackView를 사용해서 구현했습니다. `preferredLayoutAttributesFitting`를 사용해서 dynamic Cell를 구현했습니다.
https://sihyungyou.github.io/iOS-collectionView-selfsizing-cell/
- 보낸 쪽지함과 받은 쪽지함을 눌렀을 때, View가 바뀌는 걸 구현했습니다.
- reload했을 때 cell이 뭉개지는 부분이 있어서 Fix했습니다.
https://stackoverflow.com/questions/46883358/ios-preferredlayoutattributesfitting-method-did-not-invoke
- 쪽지 CollectionView를 스크롤한 후에 다른 뷰(셀이 적어서 스크롤이 안되는 뷰)로 넘어가면 large title이 안 내려오는 문제가 있어서 그 부분을 수정했는데, 이 부분이 괜찮은지 확인 받고 싶습니다. 참고 사항 …
> [ADD] Letter CollectionView Cell Layout 구현 완료

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Global/Supports/Info.plist
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- close #34 
- 개별미션 아웃라인의 색상이 미션 진행중에는 노랑으로 종료되면 흰색으로 색상 변경되게 구현했습니다.
- 진행정보에 함께했던 기록 버튼이 미션 진행중에는 안보이고 종료되면 보이도록 구현했습니다.
- 마니또 공개 버튼이 미션 진행중에는 보이고 종료되면 안보이도록 구현했습니다.
- 디자인은 스토리보드로 구현했고 진행 상황에따른 정보는 코드로 입력되어있습니다.
> [ADD] 디테일 진행중 완료 UI구현 완료

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Extension/UIColor+Extension.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailHalfModalController.swift
- close #30
- 방 정보 수정 버튼을 눌렀을때 modal이 올라오게 구현했습니다
- slider에 들어갈 이미지는 추가되면 설정하겠습니다
- 달력에 기간 설정하는 기능은 추후에 추가하겠습니다
- 적다보니 보이는데 slider에 현재인원이 몇명인지 표시를 해야겠네요
- 캘린더 내부에 주석처리한 코드는 리뷰어분들의 이해를 돕기 위함입니다. 지우고 merge예정입니다.
> [ADD] DetailView modal구현 완료

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Global/Supports/Info.plist
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- close #43 
상단 네비게이션 바, 마니띠, 마니또와의 추억 버튼, 추억 내용을 구현했습니다.
스토리보드로 작성했습니다.
폰트 사이즈는 코드로 입력되어있습니다.
> [ADD] 함께 했던 기록 UI구현

- README.md
- close #73 
리드미를 작성했습니다.
이상한 부분 있으면 말해주세요!
멘트같은건 일단 써놨습니다. 나중에 바꿀 때 수정하면 될 거 같아요!
> [DOCS] Update README

- Manito/Manito/Screens/Letter/LetterViewController.swift
- close #79 
Navigation Controller로 인해서 생긴 버그를 해결했습니다.
감사합니다. @MMMIIIN 
덕분에 해결했습니다..^^..
> [BUG] NavigationController로 인한 문제 해결

- README.md
> [DOCS] gif 파일 변경

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Literal/Size.swift
- Manito/Manito/Global/Literal/ValueLiteral.swift
- close #84
- 원활한 패딩값 수정을 위해 하나의 변수로 뺐습니다.
- 변수명 괜찮은지, 파일명 괜찮은지, 파일 위치가 괜찮은지 체크 부탁드려요 ^______^
> [CHORE] padding Literal 추가

- Manito/Manito/Global/Extension/UIColor+Extension.swift
- Manito/Manito/Global/UIComponent/MainButton.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailWaitTitleView.swift
- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Letter/UIComponent/IndividualMissionView.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterHeaderView.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterPhotoView.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterTextView.swift
- Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
- Manito/Manito/Screens/Main/Cell/ManitoRoomCollectionCell.swift
- Manito/Manito/Screens/Main/UIComponent/CommonMissonView.swift
- close #86
- 현재 grey색이 너무 많아서 남발된 색상들을 합쳤습니다.
- 현재 subBackgroundGrey라는 색상의 의도가 확실치 않아서 grey002로 바꿨는데 괜찮나요 ??
- 파일체인지 많아도 변수명 바꾼거라 부담 안가지셔도 됩니다 ^_______^
> [CHORE] color 변수 수정

- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- close #90 
- 제가 컬러변수명들 수정하는중에 코비의 코드가 머지되면서 생긴 오류를 수정했습니다.
- .subBackgroundGrey -> darkGrey002로 변경했습니다.
- 코비가 만든 ParticipateRoom 코드를 실행해 보니까 
이 flow가 맞나요 ?? 아니면 아직 덜 구현된건가요 ?? @coby5502
> [CHORE] color변수명 수정

- .github/auto_assign.yml
- close #92 
auto-reviewer를 수정합니다.
MC2 이후에도 계속해서 알림이 갈 거 같아서 수정을 해봤습니다 🥲
> [DOCS] assign-reviewer 수정

- Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputPersonView.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
close #104
제가 구현한 뷰의 패딩값 변경했습니다.
> [CHORE] 패딩값 16에서 Size.leadingTrailingPadding으로 변경

- Manito/Manito/Global/Base/BaseViewController.swift
- close #112 
- 명령을 받들었습니다 @YoonAh-dev 
- Shin의 명령입니다 불만없으시길 바랍니다 ^^
> [CHORE] 왼쪽으로 쓸어서 dismiss기능

- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailWaitTitleView.swift
- close #119 
- 115번 브랜치에서 추가적으로 작업해야했어서 그렇게 브랜치를 생성했습니다. 115번 브랜치로 머지하겠습니다
- delegate 프로토콜명이 찝찝한데 어떤식으로 작명해야 좋을까요 ?? -> Closure로 변경 완료
- calendar view의 delegate 부분이 너무 지저분한데 예쁘게 고칠 방법이 없을까요... 정작 저도 코드를 돌려봐야 상황이 이해가 가는 아주 끔찍한... ㅠ
> [FEAT] DetailEditView 모달 기능 추가 완료

- Manito/Manito/Screens/Main/MainViewController.swift
- close #136 
- 머지하는 과정에서 괄호가 날아갔습니다.
- 괄호를 추가하고 에러를 해결합니다.
> [BUG] 괄호 추가 및 에러 해결

- Manito/Manito/Global/Extension/Notification+Extension.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
close #156 
- push 로 움직였는데 풀스크린 모달을 띄우는 것으로 변경했습니다
- UI를 바꾸는 부분이라 메인쓰레드 보장을 해줬는데 괜찮나요?
- 그리고 제가 실수로 충돌해결과정에서 날려버린게 있어서 다시 살렸습니다 .. 지송
https://user-images.githubusercontent.com/59243274/186616880-8b0cb071-ab58-48bc-ae64-54d337e85d2d.mp4
> [FEAT] pushViewController 에서 모달로 바꾸고 dismiss 구현

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Network/API/DetailWaitAPI.swift
- Manito/Manito/Network/EndPoint/DetailWaitEndPoint.swift
- Manito/Manito/Network/Models/FriendList.swift
- Manito/Manito/Network/Models/Room.swift
- Manito/Manito/Network/Protocol/DetailWaitProtocol.swift
- Manito/Manito/Network/Service/APIEnvironment.swift
- Manito/Manito/Network/Service/APIService.swift
- Manito/Manito/Network/Service/NetworkRequest.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #163 
- API 연결 후 통신이 잘 되는 것 까지 확인했습니다.
- 클라쪽에서의 디자인 패턴에 대해을 어떻게 할 지 얘기가 필요할 것 같아서 우선 VC에 함수를 넣어뒀습니다.
- Model 관련 얘기도 필요해 보여서 일단 넣어뒀습니다.
- 분류한 폴더명과 파일명이 괜찮나요 ??
- 듀나의 [Havit](https://github.com/TeamHavit/Havit-iOS)을 매우 많이 참고했습니다. 감사합니다 ^________^
> [FEAT] DetailWaitView API 연결

- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterHeaderView.swift
- close #154 
쪽지 뷰 헤더 영역 텍스트를 변경했습니다. -> UX Writing
https://user-images.githubusercontent.com/55099365/187658501-7519cb8b-b7c2-4d10-80cc-60d7630dc1ff.mp4
> [CHORE] 쪽지 뷰 헤더 영역 텍스트를 변경

- Manito/Manito/Screens/Main/UIComponent/CommonMissonView.swift
- close #165 
- 메인화면의 "오늘의 공통미션" 부분의 글자 크기를 수정했습니다.
> [CHORE] 오늘의 공통미션 글자 크기 변경

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- close #170 
진행 중인 마니또 화면에서, 이미지들을 삽입하였습니다.
> [FEAT] 마니또 진행 화면, 이미지 추가

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Letter/LetterViewController+MailCompose.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- close #155 
신고하기 기능을 구현했습니다.
- 투표를 통해서 결정된 뷰로 셀을 설정했습니다.
- 서버 API가 따로 안보여서 일단은 서버 없이도 신고를 할 수 있도록 메일을 연결했습니다.
- 내부 내용은 제가 알아서 작성한 건데 혹시 태글걸고 싶으시다면 걸어도 됩니당.
https://user-images.githubusercontent.com/55099365/187690882-01198c6a-7158-4926-9a52-5f7d02fc1a8c.mp4
> [FEAT] 신고하기 기능 구현

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- resolve #178 
함께하는 친구들에서 발생하는 레이아웃 오류를 해결합니다.
이제 하단에 에러 안뜹니다.
> [FIX] 함께하는 친구들 뷰에서 생기는 레이아웃 오류 해결

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Network/API/MainAPI.swift
- Manito/Manito/Network/EndPoint/MainEndPoint.swift
- Manito/Manito/Network/Models/Room.swift
- Manito/Manito/Network/Protocol/MainProtocol.swift
- Manito/Manito/Network/Service/APIEnvironment.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- close #181 
- 케미의 멋진 코드를 따라, 잘 따라해보았습니다.
> [FEAT] MainView API 연결

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailWaitTitleView.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- close #196 
- MainView에서 해당 방으로 넘어갈 때 연결이 안 되어있는 문제를 해결했습니다.
- 진행중, 완료 방의 상태 Label을 추가했습니다.
https://user-images.githubusercontent.com/78677571/188556302-19b60c68-9960-46a4-9805-ae48b005d586.mp4
> [CHORE] MainView에서 대기방 뷰 연결, 진행중 완료 상태 Label추가

- Manito/Manito/Network/API/DetailWaitAPI.swift
- Manito/Manito/Network/EndPoint/DetailWaitEndPoint.swift
- Manito/Manito/Network/Protocol/DetailWaitProtocol.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #207 
- 방 나가기 API가 늦게 추가 됨에 따라 기능을 추가했습니다.
- 방 삭제후 바로 메인으로 나가니까 삭제한 방이 보여서 0.5초 딜레이를 줬습니다.
https://user-images.githubusercontent.com/78677571/188782027-c26333b0-bbb0-48f3-a9d4-b011f2e47ec0.mp4
> [FEAT] 방 나가기 기능 추가

- Manito/Manito/Screens/Main/MainViewController.swift
- close #204 
- MainView cell정리 이슈에서 서버분들이 정렬 해주심에 따라 코드 정리 이슈로 변경했습니다.
- 화이팅 !
> [FEAT] MainView 코드 위치 정리

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- close #206 
- 디테일 완료, 진행중의 레이아웃을 수정했습니다. 
- 오늘쪽 레이아웃이 안잡히고 왼쪽 레이아웃으로 부터 떨어져있어서 밀렸던 거더라구용
> [FEAT] 레이아웃 깨지는거 수정

- Manito/Manito/Global/Extension/UIColor+Extension.swift
- close #229 
- 피그마와 메인 레드 색상이 다른 걸 수정했습니다.
> [CHORE] MainRed색상 수정

- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterTextView.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- close #227 
`autocorrectionType`, `autocapitalizationType`를 no로 설정했습니다.
- `autocorrectionType = .no`로 설정
- `autocapitalizationType = .no`로 설정
> [FEAT] Auto Correction를 no로 설정

- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- close #237 
- 글자 제한 레이블이 화면 끝에 붙어있는걸 패딩을 줬습니다
> [CHORE] 텍스트필드 위치 조정

- Manito/Manito/Global/Literal/UrlLiteral.swift
- Manito/Manito/Network/API/DetailDoneAPI.swift
- Manito/Manito/Network/API/DetailStartingAPI.swift
- Manito/Manito/Network/API/DetailWaitAPI.swift
- Manito/Manito/Network/API/LetterAPI.swift
- Manito/Manito/Network/API/MainAPI.swift
- Manito/Manito/Network/API/RoomAPI.swift
- Manito/Manito/Network/API/SettingAPI.swift
- Manito/Manito/Network/EndPoint/DetailDoneEndPoint.swift
- Manito/Manito/Network/EndPoint/DetailIngEndPoint.swift
- Manito/Manito/Network/EndPoint/DetailWaitEndPoint.swift
- Manito/Manito/Network/EndPoint/LetterEndPoint.swift
- Manito/Manito/Network/EndPoint/MainEndPoint.swift
- Manito/Manito/Network/EndPoint/RoomEndPoint.swift
- Manito/Manito/Network/EndPoint/SettingEndPoint.swift
- Manito/Manito/Network/Service/APIEnvironment.swift
- Manito/Manito/Network/Service/NetworkRequest.swift
- Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/FriendListViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- close #234 
APIEnvironment 내부에 baseUrl이 enum으로 나눠지다보니 production과 development의 변경이 자유롭지 않다는 생각이 들어서 enum으로 나누지 않고 하나로 통일했습니다.
production server가 나오면 UrlLiteral에 production 코드를 넣어두고 사용할 예정입니다.
- 요상한 부분이 있는지만 확인해주세요
> [CHORE] APIEnviroment 코드 수정

- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- close #249 
- 방 참가이후 navigation push를 추가했습니다.
https://user-images.githubusercontent.com/78677571/190122367-7228a4eb-7686-4aa2-83bf-fea354b340ae.mp4
> [FEAT] 방 참가 이후 navigation push 추가

- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
- close #247 
- 진행중인 방에 처음 들어오면 내 마니띠를 확인하게 룰렛 뷰 분기처리를 했습니다.
- DataBinding 방식이 괜찮나요 ??
https://user-images.githubusercontent.com/78677571/190099244-c86d0a24-06e5-4669-b8bf-c24ce15fb99d.mp4
> [FEAT] 룰렛 확인에 따라 분기 처리 완료

- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Global/Resource/Storyboards/Interaction.storyboard
- close #259
- I 의 텍스트가 변경이 안되어 있어서 변경했습니다
- 레버에 관해서도 변경했습니다
> [FEAT] i수정, 레버 수정

- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- close #255 
- 마니또 공개 가능상태가 아니면 버튼을 안보이게 숨깁니다.
- Figma에는 현재 pr처럼 안보이게 설정되있긴 한데, 버튼 비활성화 상태로 한다면 나중에는 공개가 가능할거다 ! 라는 느낌을 줄 수 있지 않을까요오 ??
https://user-images.githubusercontent.com/78677571/190176778-b851d9ee-59ee-4f77-9979-ca4793a0910d.mp4
> [CHORE] 마니또 공개 버튼 isHidden

- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
- close #253 
- 방장 여부에 따라 gesture추가 함수를 분리했습니다.
- isOwner에 didSet으로 하는게 괜찮은지, 아니면 API함수 뒤에 실행하는게 좋을지 궁금합니다 !
- 다들 아까 보셨죠 ??
> [FEAT] 방장 아닌사람이 방 정보 수정 view올라오던 문제 해결

- Manito/Manito/Global/Base/BaseViewController.swift
- Manito/Manito/Global/Supports/SceneDelegate.swift
- Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/FriendListViewController.swift
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- Manito/Manito/Screens/Setting/SettingViewController.swift
- close #262 
로그아웃 구현했습니다.
- 토큰이 만료되면 로그아웃을 합니다.
- 로그아웃을 하면 로그아웃을 합니다.
> [FEAT] 로그아웃 구현

- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- Manito/Manito/Screens/Splash/SplashViewController.swift
- close #279 
- done 을 눌렀을때 키보드를 내리게 구현했습니다
- 참가하기에서 키보드 위치에 따른 버튼 위치를 조정했습니다
- 키보드가 올라와 있는 상태에서 버튼이 눌리도록 수정했습니다
https://user-images.githubusercontent.com/59243274/190902331-d380f1d7-93f0-4d1d-91ba-3c122a9e8923.mp4
> [FIX] 키보드 관련 문제들 해결

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #289 
- 시작날짜가 지났으면 날짜 설정 유도 alert이 떠야하는데 안뜨던 문제를 해결했습니다.
https://user-images.githubusercontent.com/78677571/190986575-9bd3489e-1b46-4a20-a95d-b031983a40c9.mp4
> [CHORE] 시작 기간 지났을 때 alert 안뜨던 문제 해결

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/UIcomponent/LetterCountBadgeView.swift
- close #286
- 읽지 않은 쪽지의 갯수를 뱃지로 표현합니다.
- 쪽지를 읽었다는걸 보내줘여할듯하네욤
> [FEAT] 쪽지 뱃지 추가 

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Login/LoginViewController.swift
- close #300 
사진 접근 권한 멘트를 변경했습니다.
- 리젝 사유였던 사진 접근 권한 멘트를 변경했습니다.
> [CHORE] 사진 접근 권한 멘트 변경

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- resolve #302
- 마니또 시작버튼을 활성화 하는 함수의 위치를 api함수 내부로 변경했습니다.
> [CHORE] 마니또 시작 함수 위치 변경

- Manito/Manito/Network/API/DetailWaitAPI.swift
- Manito/Manito/Network/Models/Room.swift
- Manito/Manito/Network/Protocol/DetailWaitProtocol.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- resolve #304 
- 방장의 마니띠 공개 로직을 수정했습니다.
> [CHORE] 방장의 마니띠 공개 로직 수정

- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- fix #308
닉네임이 userdefault에 설정이 되지 않는 문제를 해결합니다.
빠샤
> [FIX] nickname이 userdefault에 설정되지 않는 문제 해결

- Manito/Manito/Network/Service/APIEnvironment.swift
> [CHORE] ProductionURL로 변경

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/UIComponent/MoreButton.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #311 
- 조엘의 피드백대로 톱니바퀴 버튼에서 닷닷닷버튼으로 변경했습니다. 
- 닷닷닷버튼이 현재는 대기중인 방에서 밖에 사용되지 않는데 Global의 UIComponent로 빼뒀는데, DetailWaitView쪽으로 빼두는게 좋을까요 ??
- 그리고 이게 닷닷닷버튼이라 부르는게 아닌거 같은데 뭐라 부르나요...??
> [CHORE] 대기중 방의 톱니바퀴 버튼 -> 닷닷닷버튼으로 수정

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- close #317 
- 함수명이 didTapManito로 되어있어서 didTapManittee로 수정했습니다.
- 마니띠를 볼 수 있는 애니메이션의 속도를 조절했습니다 
2.0초 -> 1.0초 (마니띠가 보일 때 까지의 시간)
1.0초 -> 0.5초 (마니띠가 가려질 때 까지의 시간)
https://user-images.githubusercontent.com/78677571/194316930-213ae95c-b49c-4cae-81f4-ea1dc105c23d.MP4
https://user-images.githubusercontent.com/78677571/194317001-43e0a4a3-51d6-41f8-bb26-fe440c4482e6.MP4
> [CHORE] 진행중인 방에서 내 마니띠를 볼 수 있는 애니메이션의 속도를 조절했습니다.

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
애니또 대기중인 방에서 초대코드를 복사했을 때 뜨는 토스트 팝업이 답답하고 느리다는 의견이 있어서, 조금 빠르게 변경해보았습니다 !
토스트 팝업이 초대코드 복사 부분만 있는게 아니라, 방 정보를 변경했을 때도 방 정보 변경완료 ! 란 토스트 팝업이 뜹니다.
이 두개의 토스트 팝업의 속도를 조절했습니다 !
||기존 속도|개선 속도|
|---|---|---|
||![Simulator Screen Recording - iPhone 14 Pro - 2022-11-04 at 19 35 36](https://user-images.githubusercontent.com/78677571/199952743-03727a9f-31c6-459f-b64a-8933b35dbc20.gif)|![Simulator Screen Recording - iPhone 14 Pro - 2022-11-04 at 19 35 00](https://user-images.githubusercontent.com/78677571/199952839-4dc4d51d-431d-40cd-be42-29400266fca5.gif)|
|보이기|1.5초|0.7초|
|딜레이|0초|1초|
|사라지기|1.5초|0.7초|
기존의 방식은 1.5초 동안 alpha값을 1로 변경하고(안보이다가 보이고), 바로 1.5초 동안 다시 alpha값을 0으로 변경하는(보이다가 안보이게) 방식을 썼는데, 개선한 방식은 0.7초 동안 alpha 값을 1로 변경하고, 보이는 상태로 1초동안 딜레이 시간을 갖고, 0.7초 동안 alpha 값을 0으로 변경시키는 방식으로 구현했습니다 ! …
> [CHORE] 토스트 팝업 속도 조절

- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Network/API/DetailDoneAPI.swift
- Manito/Manito/Network/EndPoint/DetailDoneEndPoint.swift
- Manito/Manito/Network/Protocol/DetailDoneProtocol.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
완료된 애니또 방이 많이 쌓이는데 그걸 처리할 방법이 없어서, 나가기 기능이 필요하다는 의견이 있었습니다.
완료된 방에 한해서 방 나가기 기능을 추가했습니다. 
- 그 방의 방장일 때는 나가기 버튼을 누르면 
`"방장은 방을 나갈 수 없어요"`라는 alert이 표시가 됩니다. (방장은 방을 나갈 수 없기 때문에 좋지 못하다 생각합니다) 
방장이 방을 나갈 수 있는 방법은 방을 삭제하는 방법인데, 방을 삭제하면 다른 유저들도 그 방이 사라지기 때문에 굉장히 위험하다 생각합니다.
- 방장이 아닐 때는 방 나가기 버튼을 누르면 
위와 같이 alert이 표시됩니다. 확인 버튼을 누르면 방이 나가지고 
`navigationController?.popViewController(animated: true)` 해당 코드가 실행되면서 뒤로가게 됩니다.
feature/336-postroom-exit 브랜치로 오셔서 완료된 방중에 본인이 만든 방이 아닌 방을 나가기 눌러보시면 됩니다.
완료된 방중에 제가 방장이 아닌 방이 2개밖에 없었는데, 코드짜면서 둘 다 나가버려서 영상 찍을 방이 없습니다.... 혹시 다른분이 제 브랜치로 오셔서 정상 동작하는것 좀 찍어주십셔... 
방장일때 나갈 수 없다는 alert을 표시하는 영상은 있습니다.
https://user-images.githubusercontent.com/78677571/200128925-07e0db14-34b8-4118-b0b4-fa6572aee7d2.mp4
- 위의 스크린샷에서도 든 생각인데, api를 테스트하기 위해서 실제 방이 있어야하고, 너무 제한적이라는 생각이 …
> [FEAT] 완료된 방 나가기 기능 추가

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Extension/UIColor+Extension.swift
- Manito/Manito/Global/Supports/SceneDelegate.swift
- Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
1차 배포에는 몇 개의 뷰가 storyboard로 작성되었습니다. 이번 스프린트 때 codebase로 바꾸려는 계획을 세웠습니다. 이번 PR에서는 Detailing뷰의 프로퍼티를 생성했고, 연결되어 있는 기본 함수를 print 액션을 주어 연결했습니다.
먼저 DetailngCodebaseViewController 파일을 생성했습니다. Detailing뷰의 프로퍼티를 생성했고, 연결되어 있는 기본 함수를 print 액션을 주어 연결했습니다. 현재는 뷰에 있는 모든 프로퍼티는 일단 다 띄운 상태입니다. 마니또 공개 버튼, 함께 했던 기록도 일단 띄운 상태입니다 다음 PR 때는 고려하여 수정하도록 하겠습니다.
feature/325-change-to-codebase 브랜치로 오셔서 SceneDelegate 파일로 가서 밑에 그림처럼 수정을 해주시면 됩니다.
이후 DetailngCodebaseViewController 파일에서 실행시키면 됩니다,
액션이 있는 프로퍼티를 누르면 print문에 해당 내용이 출력되는 것을 확인하시면 됩니다.
뷰를 짜면서 그동안의 여러분들이 노력하여 만드신 코드를 공부했습니다. 다음 PR때는 데이터 통신까지 공부하여 완벽하게 구현하도록 하겠습니다. 감사합니다 :)
- close #325
> [ADD] Detailing 뷰 Storyboard -> Codebase

- Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
- Manito/Manito/Screens/CheckRoom/UIComponent/PeopleInfoView.swift
- Manito/Manito/Screens/CheckRoom/UIComponent/RoomInfoView.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/ChooseCharacter/UIComponent/CharacterCollectionViewCell.swift
- Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
- Manito/Manito/Screens/Main/Cell/ManitoRoomCollectionCell.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/Main/UIComponent/CommonMissonView.swift
- Manito/Manito/Screens/Main/UIComponent/RoomStateView.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
예전에 짰던 코드에서, 아쉬운 코드가 많아서 전체적으로 리펙토링을 진행하였습니다.
메인화면에서부터 방을 참가하는 플로우에서의 뷰들의 UI를 제가 작업했어서, 관련된 뷰들을 수정하였습니다.
아래 뷰컨들과 셀들의 코드를 수정했습니다.
- MainViewController
- ParticipateRoomViewController
- CheckRoomViewController
- ChooseCharacterViewController
다음 위주로 수정했습니다.
- class와 view에 final 붙이기
- private / lazy var / var / let 새로 정해주기
- 주석 달지 않은 부분 새로 달기
- 주석에 맞지 않는 함수 위치 옮기기
- 쓰지 않는 함수 및 변수 삭제
- close #343
> [REFACTOR] 메인 화면 및 방참가 코드 리펙토링

- Manito/Manito.xcodeproj/project.pbxproj
다시 개발용 브랜치인 develop에 v1.2버전 상태를 업데이트 합니다.
> [CHORE] v1.2 출시에 따른 develop 브랜치 업데이트

- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Base/BaseViewController.swift
- Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
- Manito/Manito/Screens/Detail-Ing/FriendListViewController.swift
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Interaction/OpenManittoPopupViewController.swift
- Manito/Manito/Screens/Interaction/OpenManittoViewController.swift
- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
- Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/LetterImageViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController+MailCompose.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Login/LoginViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- Manito/Manito/Screens/Setting/SettingViewController.swift
- Manito/Manito/Screens/SettingDeveloperInfo/SettingDeveloperInfoViewController.swift
저번에 정했던 code convention를 적용했습니다.
BaseViewController에 있는 render, configUI가 변경되면서 파일 체인지가 많이 생겼습니다. 집중해서 볼 코드는 없으니 봐주십쇼..🙏
Letter 스크린 내부에 있는 모든 파일들의 code convention를 맞추려고 했지만, BaseViewController 내부에 있는 render, configUI 함수를 setupLayout, configureUI로 바꾸면서 files changed가 늘어났습니다. 따라서, 해당 PR 머지 후에 같은 브랜치에서 cell, ui component들의 code convention를 맞출 예정입니다.
- close #370
> [CHORE] Letter 스크린 폴더 내부에 있는 ViewController 파일들의 code convention를 맞췄습니다.

- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailWaitTitleView.swift
노션에 정리되어 있는 각각의 컨벤션들이 맞지 않는 부분을들 수정했습니다.
1. self 명시
2. 주석 위치와 이름 변경
3. 파라미터 여려개일때 줄 바꾸기
4. 컴포넌트 네이밍 수정
5. final 키워드 명시
6. render -> setupLayout 이름 변경 (BaseViewController를 상속 받지 않는 UIView)
feature/376-detailwait-convention 브랜치로 오셔서 
요기 파일들을 작업했으니 혹시 놓친 부분이 있다면 말씀 부탁드립니다 !
삼항 연산자에 대해선 컨벤션을 정하지 않았더라구요 !
중간에 삼항 연산자가 너무 길어서 임의로 줄 바꾼 부분이 있는데 따로 컨벤션을 만들면 어떨까 싶습니다. 하지만 어느정도가 길다고 느끼는지는 조금 애매하긴 하네요...
- close #376
> [CHORE] 대기중 방의 코드 컨벤션을 적용했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Letter/UIComponent/BottomOfSendLetterView.swift
- Manito/Manito/Screens/Letter/UIComponent/CreateLetterPhotoView.swift
- Manito/Manito/Screens/Letter/UIComponent/CreateLetterTextView.swift
- Manito/Manito/Screens/Letter/UIComponent/IndividualMissionView.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterHeaderView.swift
저번 UIViewController 파일들에 이어서 UIComponent 폴더에 있는 파일들도 컨벤션을 맞췄습니다.
*아직 Cell은 컨벤션을 맞추지 않았습니다. 코비가 올려주신 #375 PR에서 해당 Cell 부분을 건드려서 해당 PR이 머지되고 나서 진행할 거 같습니다.
저번에 수정했던 컨벤션으로 전체적인 코드를 수정했습니다. 혹시 잘못 수정했거나 아직 수정이 안된 부분이 있다면 코멘트 달아주세요!
함수 네이밍이 별로인 부분들이 많아서 진행하면서 함수 네이밍을 변경했습니다. 네이밍은 Apple Document  API들의 네이밍 방식을 최대한 따라해보려고 했습니다. 문법적인 오류라던지 이해가 안되는 함수가 있다면 지적해주십쇼.
현재 있는 함수 내부에서 하는 일이 너무 많은 거 같아서 최대한 다른 함수로 빼는 작업을 진행했습니다. 이 부분은 `CreateLetterPhotoView`에서 대부분 일어났습니다. 따라서 `CreateLetterPhotoView`에서만 집중해서 봐주시면 됩니다.
internal로 접근 제한자가 설정되어 있는 메소드, 프로퍼티들을 최대한 private으로 변경하려고 노력했습니다.
feature/370-correct-convention
해당 브랜치로 오셔서 봐주시면 됩니다. CreateLetterPhotoView는 바뀐 부분이 많은지 새 파일을 만든것처럼 file changed에서 보이네요.🥲
⓵ 현재 카메라를 통해서 사진을 가져올 때, 카메라에 대한 접근 권한이 없으면 따로 alert가 뜨지 않고 검은 화면으로 넘어갑니다. 라이브러리 접근 권한이 없을 때 설정으로 보내주는 것처럼 …
> [CHORE] Letter > UIComponent 폴더에 포함되어 있는 UIView들의 컨벤션을 맞췄습니다.

- .github/release.yml
- .github/workflows/release-drafter.yml
애니또 릴리즈 노트에 있는 내용을 매번 손수 쓰는게 번거롭고 시간이 많이 드는 일이라서 이 부분을 자동화할 수 없을까 해서 시작하게 되었습니다.
템플릿만 만드려고 했는데 github action으로 market에 제공되어 있는 release drafter를 찾아서 이를 사용해서 main에 push 되었을 때 노트가 자동으로 생성(published 직전)되도록 했습니다.
해당 파일은 github action market에 올라가 있는 [`Release Drafter`](https://github.com/marketplace/actions/release-drafter#template-variables)를 사용하기 위해서 만들었습니다. 
내용에서 보시다시피 main 브랜치에 push, 즉 머지되었을 때 Action이 run하도록 코드를 짰습니다. 혹시 추가하고 싶으시거나 수정해야할 내용이 있다면 알려주세요!
```YAML
name: Release Drafter
on:
push:
branches:
- main
permissions:
contents: read
jobs:
update_release_draft:
permissions:
contents: write
runs-on: ubuntu-latest
steps:
- uses: release-drafter/release-drafter@v5
with:
config-name: release.yml
env:
GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```
<br>
해당 YAML 파일은 main 브랜치에 push 되었을 때 생성되는 …
> [DOCS] Release 노트를 구성하는 YAML 파일을 생성하고 노트 생성 자동화를 진행했습니다.

- Manito/Manito/Global/Base/BaseCollectionViewCell.swift
- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Screens/ChooseCharacter/UIComponent/CharacterCollectionViewCell.swift
- Manito/Manito/Screens/Detail-Ing/Cell/MemoryCollectionViewCell.swift
- Manito/Manito/Screens/Interaction/Cell/ManittoCollectionViewCell.swift
- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
- Manito/Manito/Screens/Main/Cell/ManitoRoomCollectionCell.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/Main/UIComponent/CommonMissionView.swift
- Manito/Manito/Screens/Main/UIComponent/RoomStateView.swift
- Manito/Manito/Screens/SettingDeveloperInfo/Cell/DeveloperInfoViewCell.swift
Main 폴더 내부의 파일들을, 코드 컨벤션에 따라 수정했습니다.
지난 번에 듀나가 수정한 BaseViewController에 이어, BaseCollectionViewCell에 render()와 configUI()의 rename이 이루어졌습니다.
따라서 Main폴더 외부의 파일에도 수정이 다소 있습니다.
- close #372
> [CHORE] Main 폴더 내부 컨벤션 정리

- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
Letter Screen 폴더에서 코드 컨벤션을 적용하지 않은 Cell 파일이 있어서 이를 적용했습니다.
LetterCollectionViewCell 파일에 코드 컨벤션을 적용했습니다.
- close #394
> [CHORE] LetterCollectionViewCell에 코드 컨벤션을 적용했습니다.

- Manito/Manito/Network/API/LetterAPI.swift
- Manito/Manito/Network/EndPoint/LetterEndPoint.swift
- Manito/Manito/Network/Models/Letter.swift
- Manito/Manito/Network/Protocol/LetterProtocol.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
쪽지에 미션이 보여지도록 수정이 되어서 이를 반영했습니다.
missionId를 넣어야지 mission이 있는 쪽지가 만들어져서 이 부분을 추가했습니다.
```swift
func dispatchLetter(roomId: String, image: Data?, letter: LetterDTO, missionId: String) async throws -> Int
```
mission 데이터를 추가해서 mission이 있다면 받아올 수 있도록 수정했습니다.
```swift
struct Message: Codable {
var id: Int?
var content: String?
var imageUrl: String?
var createdDate: String?
var missionInfo: Mission?
var mission: String? {
guard let mission = missionInfo?.content else { return nil }
return "\(date)의 개별미션\n[\(mission)]"
}
}
```
이전에는 하단에 날짜 라벨이 위치하고 있어서 이를 위로 옮겼습니다. 
+) 날짜에 맞춰서 색깔이 변경되도록 수정했습니다. 근데 수정된 라벨말고 date만 뜨는 라벨도 오늘일 경우에 노란색을 입혀야 하나요..? 일단은 오늘이면 다 노란색으로 뜨도록 했습니다.
| 이전 | 현재 |
|--|--|
|<img width="551" alt="스크린샷 2023-03-03 오후 11 35 17" …
> [FEAT] 쪽지에 미션을 보여주는 라벨을 추가했습니다.

- Manito/Settings.bundle/com.mono0926.LicensePlist.latest_result.txt
- Manito/Settings.bundle/com.mono0926.LicensePlist.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/GoogleAppMeasurement.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/GoogleDataTransport.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/GoogleUtilities.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/SkeletonView.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/abseil-cpp-SwiftPM.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/boringssl-SwiftPM.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/firebase-ios-sdk.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/grpc-ios.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/gtm-session-fetcher.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/leveldb.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/nanopb.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/promises.plist
- Manito/Settings.bundle/com.mono0926.LicensePlist/swift-protobuf.plist
새로운 라이브러리들을 추가했지만 아직 오픈소스 라이센스 창은 업데이트가 안되어 있어서 이 부분을 업데이트해주었습니다.
파일 체인지가 많은데, 오픈소스 라이센스 내용이 많이 추가되면서 체인지가 많아졌습니다.
- 새로운 라이브러리를 추가했습니다.
- 이전과는 다르게 라이브러리의 버전이 옆에 뜨도록 수정했습니다.
오픈소스 라이센스 창 만드는 법은 [노션 블로그](https://yoonah-dev.oopy.io/e3f8c794-8a32-4669-8ccf-2d4810e124b1)에 정리해뒀습니다.
해당 브랜치에서 빌드 돌린 후 설정 화면 > 애니또 > 오픈소스 라이센스 > 해당 부분에 라이브러리가 잘 들어오는지 확인
- close #408
> [ADD] 오픈소스 라이센스 창에 새로운 라이브러리를 추가했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
v1.3.0 출시에 따라 develop 브랜치를 업데이트합니다.
> [CHORE] 배포된 v1.3.0을 develop 브랜치로 가져옵니다

- Manito/Manito.xcodeproj/project.pbxproj
v1.4.0 출시에 따라 develop 브랜치를 업데이트합니다!
> [CHORE] v1.4.0에 따른 develop 브랜치 업데이트

- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Network/Models/FriendList.swift
- Manito/Manito/Screens/Detail-Ing/FriendListViewController.swift
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- Manito/Manito/Screens/Interaction/Cell/ManittoCollectionViewCell.swift
- Manito/Manito/Screens/Interaction/OpenManittoPopupViewController.swift
- Manito/Manito/Screens/Interaction/OpenManittoViewController.swift
- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
Interaction(마니또 공개, 마니또 선정) 화면에 코드 컨벤션을 적용했습니다.
코드 컨벤션 적용 브랜치라서 큰 구현 사항이 없습니다. 따라서 간단한 설명만 써두겠습니다.
- `OpenManittoViewController` 에 코드 컨벤션 적용
- `SelectManittoViewController` 에 코드 컨벤션 적용
- `OpenManittoPopupViewController` 에 코드 컨벤션 적용
- `ManittoCollectionViewCell` 에 코드 컨벤션 적용
OpenManittoPopupVC, SelectManittoVC가 Storyboard를 사용하고 있어서 
1. init를 제대로 활용하지 못하고 
2. View 분리 시에 분리 코드를 짜기 복잡할 것 같아서 
3. 전체적으로 Storyboard를 사용하지 않고 Code-based UI로 짜고 있는데 이 부분만 Storyboard로 짜니깐 코드를 짜다가 왜 이부분은 이렇게 짰지 하고 이해가 안되는 상황들이 발생해서 
4. 프로젝트 전반적인 추세를 따르기 위해서 
스토리보드를 제거합니다.
- close #426
> [CHORE] Interaction 화면에 코드 컨벤션을 적용했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
v1.5.0 출시에 따라 develop 브랜치를 업데이트 합니다.
> [CHORE] v1.5.0 출시에 따라 develop 브랜치를 업데이트 합니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/xcshareddata/xcschemes/Manito.xcscheme
- Manito/ManitoTests/ManitoTests.swift
테스트 코드의 첫 발걸음인 타겟을 추가했습니다.
현재 프로젝트에 테스트를 적용해보고 싶은데, 프로젝트 자체에 추가가 안되어 있어서 가장 기본작업인 타겟 추가를 했습니다.
Unit Test Target추가
테스트를 어떤 식으로 작성할 것인지에 대해서는 아직 얘기된 부분이 없기도 하고, 제 뷰에서 연습을 해보고 싶어서 타겟만 먼저 추가했습니다.
적절한 단위별로 폴더 구조를 만들어서 각자의 테스트 코드를 작성해도 좋을 것 같습니다
- close #454
> [SETTING] 테스트코드 작성을 위한 Target을 추가했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Network/Models/Request/RoomDTO.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/ChooseCharacter/UIComponent/CharacterCollectionViewCell.swift
- Manito/Manito/Screens/ChooseCharacter/UIComponent/ChooseCharacterView.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/CreateRoom/UIComponent/CharacterCollectionView.swift
- Manito/Manito/Screens/CreateRoom/UIComponent/ChooseCharacterView.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
#423 PR 에서 생긴 문제로, 방을 생성하는 플로우인 (방제목입력 -> 인원수 입력 -> 날짜 입력 -> 확인 ) 여기에  (케릭터 선택) 이 합쳐져야 하기 때문에 일단 그 첫번째 단계로 `ChooseCharacterViewController` 를 View 분리하는 PR입니다.
제가 이 뷰를 나누면서 고민했던 부분은 View로 분리하며 캐릭터를 선택하는 collectionView 는 따로 컴포넌트 화 시키는 것이었습니다. 그 이유는 
마니띠를 선택하는 collectionView (이하 `CharacterCollectionView`) 는  2곳에서 사용이 됩니다.
- 방 생성시 플로우 ( 방 제목 입력 -> 인원수 입력 -> 날짜 입력 -> 확인 -> 캐릭터 선택) 
- 방 참여시 플로우 ( 초대코드 입력 -> 캐릭터 선택)
그런데 방생성 플로우에 사용되는 부분은 `CharacterCollectionView` 부분만 바뀌도록 설정할 생각이고 (스탭에 따라 안에 뷰만 바뀌는 형식)
방 참여 플로우 에선 아예 `ChooseCharacterViewController`가 사용이 됩니다. 그래서 아래 그림과 같이 구현할 예정이고 첫번째 단계인 View를 분리했습니다.
개발 순서)
1. `ChooseCharacterViewController` View 분리 (현 PR)
2. `ParticiapantViewController` View 분리  (#457 )
3. `CreateRoomViewController` 에 `CharacterCollectionView` 연결 423 PR
ViewController에서는 View의 …
> [REFACTOR] ChooseCharacterViewController를 View 분리, 컨벤션 적용

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomView.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
현재 저희가 지향하는 MVC 모델로 리팩토링 하는 작업 입니다. 
이 PR은 #455 을 pull 받은 후 진행된 작업입니다. 455PR 이후에 리뷰 해주시면 감사하겠습니다.
- ParticipateRoomViewController 와 ParticipateRoomView 분리
- 이전 PR 에서 생긴 navBar 문제 해결
`feature/456-participate-refactor` 로 오셔서 방 참여 화면을 보시면 됩니다.
- close #456
> [REFACTOR] ParticipateRoomViewController 를 View와 분리하였습니다.

- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Global/Extension/UIButton+Extension.swift
- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Screens/Setting/SettingViewController.swift
- Manito/Manito/Screens/Setting/View/SettingView.swift
저희 앱의 서비스 탈퇴 ui 를 구현했습니다.
| Figma | 구현 화면 |
| ------| ---------|
| <img src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/c476a946-a631-4af2-84ef-685bde3eb6d4" width="350">         | <img src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/f2b3feb0-b5f1-4ee5-bd08-11d9e90b3335" width="350">            |
` feature/460-setting-withdrawal` 로 오셔서 확인해보시면 됩니다. 
- 현재는 api 가 없어서 api 연결은 내일 회의 이후에 진행하도록 하겠습니다 감사합니다.
- close #460
> [FEAT] 서비스 탈퇴 기능 UI 구현

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Extension/Publisher+Extension.swift
- Manito/Manito/Screens/Letter/ViewModels/LetterViewModel.swift
- Manito/Manito/Screens/Letter/Views/ViewControllers/LetterViewController.swift
async 메서드는 따로 Subject를 만들어서 데이터를 Stream으로 보내줘야 하는 점이 불편하다고 생각이 들어서 async 메서드를 사용할 수 있는 asyncMap 메서드를 만들었습니다.
Publisher extension에서 asyncMap를 추가로 만들었습니다. 
⓵ 아무런 에러도 반환하지 않고 success 데이터만 반환하는 asyncMap
⓶ 에러도 반환하는 asyncMap
⓷ Publishers에서도 사용할 수 있는 에러 반환 asyncMap
3가지를 추가로 만들었습니다. 3가지 asyncMap은 [해당 깃헙](https://github.com/boostcampwm-2022/iOS09-burstcamp/blob/develop/burstcamp/burstcamp/Util/Extension/AsyncCompatible/Publisher%2BAsync.swift)을 참고해서 만들었습니다.
asyncMap을 직접 적용한 코드가 있어야 사용하는데 무리가 없을 것 같아서 Letter ViewModel에 추가해서 사용해봤습니다.
이전 코드에서 `Task` 부분이 사라지고 더이상 따로 Subject를 사용하지 않아도 된다는 점 빼고는 모두 동일하기 때문에 코드를 보는데 무리가 없을 것으로 판단했습니다. 그래도 이해하기 어려운 점이 있다면 코멘트 달아주세요.
asyncMap에서 NetworkError로 반환하지 않은 이유는 네트워크 코드에서만 asyncMap를 쓰는게 아니라서 그렇습니다.
해당 브랜치에서 빌드가 제대로 되는지 + letter 화면에서 잘못되는 부분은 없는지 확인해주시면 됩니다. …
> [FEAT] async 메서드를 사용할 수 있는 AsyncMap를 Extension에 추가했습니다.

- .github/auto_assign.yml
auto-assign 되는 멤버를 수정해야 할 듯 하여 오랜만에 멤버 수정을 진행했습니다.🙇‍♂️
크게 진행한 작업이 없습니다.🙇‍♂️
- close #495
> [DEL] auto-assign.yml 파일 멤버를 수정했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Domain/Entity/DefaultCharacterType.swift
- Manito/Manito/Domain/Entity/RoomStatus.swift
- Manito/Manito/Screens/CreateRoom/UIComponent/CharacterCollectionView.swift
- Manito/Manito/Screens/Detail-Ing/Cell/FriendCollectionViewCell.swift
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- Manito/Manito/Screens/Interaction/Cell/OpenManittoCollectionViewCell.swift
Character Type 네이밍을 수정하고 enum 내부 케이스와 변수 네이밍도 수정했습니다.
간단한 PR이니 이해하기 어려운 부분은 없을 것으로 생각이 됩니다.
**⓵ Character를 DefaultCharacterType으로 이름 수정**
기본 캐릭터 타입이라는 느낌을 주기 위해서 네이밍을 `DefaultCharacterType`으로 수정했습니다.
혹시 다른 이름이 좋을 것 같다거나 원래 네이밍이 좋을 것 같다면 코멘트로 말씀해주세요.🙇‍♂️
**⓶ 케이스 패턴 이름 수정**
케이스 패턴 네이밍이 Image에서 사용하는 이름으로 설정되어 있어서 적절하지 않다는 생각이 들었습니다.
간단하면서도 이해할 수 있는 색깔로 네이밍을 했습니다.
```swift
enum DefaultCharacterType: CaseIterable {
case pink
case brown
case blue
case red
case orange
case yellow
case lightGreen
case heavyPink
case purple
}
```
**⓷ 배경 색깔 변수 이름을 수정했습니다.**
이전에 `color`로 되어 있던 변수를 `backgroundColor`로 이름을 변경하여 배경 색깔이라는 것을 명확하게 했습니다.
- close #522
> [CHORE] Character Type 네이밍 수정 및 내부 코드 정리를 진행했습니다.

- Manito/Manito/Domain/Entity/IndividualMission.swift
- Manito/Manito/Domain/Entity/InvitationCode.swift
- Manito/Manito/Domain/Entity/MessageCountInfo.swift
- Manito/Manito/Domain/Entity/ParticipantList.swift
- Manito/Manito/Domain/Entity/RoomInfo.swift
- Manito/Manito/Domain/Entity/RoomListItem.swift
- Manito/Manito/Domain/Entity/UserInfo.swift
- Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
- Manito/Manito/Util/Extension/Type/Date+Extension.swift
- Manito/Manito/Util/Extension/Type/String+DateFormatter.swift
듀나와 호야가 앞서 다른 Entity들에 설명 주석을 달아주셔서 이해하기 한결 수월했습니다. 제 담당 뷰에서 사용하는 Entity들에 대해 설명 주석을 추가했습니다.
1. 각 Entity에 설명을 추가했습니다.
2. 전혀 사용되고 있지 않은 값들을 삭제했습니다.
3. 설명이 있으면 좋겠다 싶은 Extension에도 주석을 추가했습니다.
전혀 사용되고 있지 않은 값들 빼곤 코드를 건드린 부분이 없어서 주석만 확인해주시면 됩니다 ^_________^
주석이 필요 없는 코드가 좋은 코드라는건 알고 있지만, 추가적으로 주석을 통해 더 명확히 하고 실수를 줄일 수 있다면 그게 더 좋은 개발 방법 같습니다!
주석 짱 👍
- close #541
> [CHORE] 방 정보와 관련된 Entity에 설명 주석을 추가했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Data/Error/CreateRoomScene/CreateRoomError.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/CreateRoom/Services/CreateRoomService.swift
- Manito/Manito/Screens/CreateRoom/ViewModel/CreateRoomViewModel.swift
방생성에 실패하면 현재는 
이런식으로 나오는데 사실 이 부분도 실행이 안될겁니다. CreateRoomService 에서 NetworkError 를 캐치하도록 설정되어 있는 부분을 수정했습니다. 
그리고 방생성 플로우를 종료하기 보단, 다시 실행할 수 있는 UX 가 좋지 않을까? 생각해서 Result 타입으로 에러처리를 했습니다.
+) 추가로.. 여기서 할게 아니였는데 Service 에 대한 추상화를 진행헀습니다. 다음 PR에서 CreateRoom에 대해 리팩토링을 다시 한번 진행할 것 같네요.
- 방 생성 에러 추가
- Service 추상화
`feature/583-createRoomVC-error` 에 오셔서 방생성을 해보시거나 (성공)
`RoomParticipationEndPoint` 에서 dispatchCreateRoom의 path를 살짝 수정해서 실행해보면 실패합니다. 그때 에러메세지를 보시면 됩니다. 
| 방 생성 성공 | 방 생성 실패 |
|------------| ------------|
|   <img src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/6b1ad5ab-29f8-4b4d-9496-c6806c1452f8" width="350">          |     <img src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/506c3b96-91c7-4277-9492-eff86f00b124 …
> [CHORE] CreateRoom 관련해 Error 를 추가했습니다. 

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Data/Repository/DetailRoomRepositoryImpl.swift
- Manito/Manito/Data/Repository/LetterRepositoryImpl.swift
- Manito/Manito/Data/Repository/LoginRepositoryImpl.swift
- Manito/Manito/Data/Repository/MainRepositoryImpl.swift
- Manito/Manito/Data/Repository/RoomParticipationRepositoryImpl.swift
- Manito/Manito/Data/Repository/SettingRepositoryImpl.swift
- Manito/Manito/Data/Repository/TokenRepositoryImpl.swift
- Manito/Manito/Domain/Repository/DetailRoomRepository.swift
- Manito/Manito/Domain/Repository/LetterRepository.swift
- Manito/Manito/Domain/Repository/LoginRepository.swift
- Manito/Manito/Domain/Repository/MainRepository.swift
- Manito/Manito/Domain/Repository/RoomParticipationRepository.swift
- Manito/Manito/Domain/Repository/SettingRepository.swift
- Manito/Manito/Domain/Repository/TokenRepository.swift
기존 저희 코드에선 Repository 인터페이스인 프로토콜이 Data 영역에 위치하였습니다. 물론 코드 상으로 문제는 하나도 없지만 영역을 나누는게 좋다고 생각되어 회의를 거친 후 작업하게 되었습니다. 
- Data 영역에 있던 protocol 을 Domain 영역으로 옮김
폴더 위치만 변경했습니다. 
각 영역별로 프레임워크로 분리하여 사용하는게 제 목표입니다....
- close #587
> [REFACTOR] Repository 를 Data 영역에서 Domain 영역으로 분리하였습니다. 

- Manito/Manito/Screens/NickName/ViewControllers/CreateNicknameViewController.swift
닉네임 설정 뷰에서 삭제된 Main 스토리보드에 연결이 되어있어서 크래쉬가 났습니다. 
스토리보드가 아닌 MainViewController 로 연결
회원탈퇴를 진행한 뒤 닉네임 생성 프로세스를 하셔야하는데 부담되시면 스크린샷을 참고해주시면 됩니당.
- close #590
> [BUGFIX] Main 스토리보드 삭제에 따른 앱 Crash 버그를 수정했습니다. 

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Domain/Entity/RoomListItem.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
- Manito/Manito/Screens/InvitedCode/View/InvitedCodeView.swift
- Manito/Manito/Screens/InvitedCode/ViewModel/InvitedCodeViewModel.swift
- Manito/Manito/Util/Literal/en.lproj/Localizable.strings
InvitedCodeViewController 가 아직 리팩토링이 되어있지 않아 진행했습니다. 
1. View와 ViewController 분리
2. ViewModel 생성
3. 데이터 바인딩
`feature/594-invitedCodeVC-refactor` 에 오셔서 방생성한번 해보시면 됩니당
현재 code 부분을 viewDidLoad 시와 복사 버튼을 클릭했을때 2번 방출하고 있는데, 그렇게 말고 View에 code를 ViewDidLoad시만 전달하고 값을 가지고 있다가 복사하는걸로 할까요? 뭐가 좋을까 모르곘네용
1. code를 2번 방출하는 방식 / view에서 code를 가질 필요없음
2. code를 viewDidLoad에서만 방출하고 view에서 code를 갖고 있는 방식
- close #594
> [REFACTOR] InvitedCodeViewController 를 Combine + MVVM 으로 리팩토링 했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Data/Error/ParticipateRoomScene/ChooseCharacterError.swift
- Manito/Manito/Data/Error/ParticipateRoomScene/ParticipateRoomError.swift
- Manito/Manito/Data/Repository/RoomParticipationRepository.swift
- Manito/Manito/Domain/Entity/ParticipatedRoomInfo.swift
- Manito/Manito/Domain/Usecase/ParticipateRoomScene/ParticipateRoomUsecase.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/View/ChooseCharacterView.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/View/ParticipateRoomView.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/View/ParticipationRoomDetailsView.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/View/UIComponent/InputInvitedCodeView.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewController/ChooseCharacterViewController.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewController/ParticipateRoomViewController.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewController/ParticipationRoomDetailsViewController.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewModel/ChooseCharacterViewModel.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewModel/ParticipateRoomViewModel.swift
- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewModel/ParticipationRoomDetailsViewModel.swift
- Manito/Manito/Util/Literal/en.lproj/Localizable.strings
코드를 조금 더 고 벨류로 올렸습니다. ^_^ 
작업 내용이 많아보이지만 사실 보기에 어렵거나 많지 않을겁니다. !!
**1. ViewModel 추상화**
VC에 있는 viewModel을 추상화 시켜 의존성을 주입하는 방식으로 변경 했습니다.
**2. AnyPublisher 캡슐화**
VM 에 있는 Output의 타입을 AnyPublisher 로 캡슐화했습니다.
추가로 subject 로 있던것들을 삭제했습니다 ^_^
**3. usecase 추상화**
VM에 있는 usecase를 추상화 시켜 의존성을 주입하는 방식으로 변경 했습니다.
**4. 네이밍 변경**
request로 되어있는 네트워크 관련 코드를 코드 컨벤션에 맞게 변경했습니다.
**5. Error 추가 및 처리**
방 참가 에러를 추가했습니다.  Result 타입으로 에러처리를 했어요! 
**6. Helper 분리**
present 관련이나 네트워크 코드를 Helper 마크로 옮겼습니다. 
**7. 타입 명시**
저희가 combine 타입을 사용하면서 타입 어노테이션 코딩 컨벤션을 지키지 않고 있더라고요! 타입 어노테이션을 진행헀습니다.
`feature/596-participateScene-refactor` 오셔서 방 참여 관련 로직 수행하보시면 됩니당
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/d7cb912b-1913-48f4-b76b-9c2c13e372cb
어제보다 오늘이 더 높은 퀄리티의 코드를 짜자..! 
- close #596
> [REFACTOR] 방 참여 관련 씬의 코드를 정리하였습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Data/Error/SettingScene/SettingError.swift
- Manito/Manito/Domain/Usecase/SettingScene/SettingUsecase.swift
- Manito/Manito/Presentation/Scene/SettingScene/View/SettingView.swift
- Manito/Manito/Presentation/Scene/SettingScene/View/UIComponent/TopCharacterImageView.swift
- Manito/Manito/Presentation/Scene/SettingScene/ViewController/SettingViewController.swift
- Manito/Manito/Presentation/Scene/SettingScene/ViewModel/SettingViewModel.swift
- Manito/Manito/Screens/Login/LoginViewController.swift
subject 의 남발, 추상화 등등 코드 품질을 높일 수 있겠다 싶어서 진행하였습니다.
- ViewModel 추상화
- Type annotation
- usecase 추상화
- Helper 로 분리
- deleteUser 로직 변경
- logout로직 변경
- SettingError 생성
- 컨벤션 통일
`feature/602-setting-refactor` 에 오셔서 로그아웃이랑 회원탈퇴 진행해보시면 됩니당.
그치만 회원탈퇴는 너무 아쉽겠죠? 제가 스크린샷을 첨부했으니 그걸로 구동여부는 확인해주세용
| 로그아웃 | 회원탈퇴 |
|---------| --------|
|<img src = "" width = "350">        | <img src = "" width = "350">            |
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/d831863c-a5d7-4575-8288-aefd38042e52
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/c9dc5ed0-4954-4ade-a3e3-74eb8be2b913
제가 맡은 부분은 이제 끝이네요! 앞으로 코드 품질을 높이는 경우는 분명 있겠지만 애니또 2023목표에.. 다가왔습니다!
- close #602
> [REFACTOR] SettingScene 에 있는 코드들의 품질을 향상 시켰습니다.
