- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #32 
- 방장과 참여자 둘 다 톱니바퀴 설정버튼으로 수정했습니다.
- 추후에 참여한 사람의 캐릭터를 바꿀 수 있게 설정버튼에 추가할 예정입니다.
- 나가기 모양의 버튼이었을때 바로 나가기 Alert창이 떠서 나가는 것에 대한 위험이 있었는데 중간에 menu를 넣음으로써 depth가 깊어졌습니다.
- 251번째 줄 부터 275번째 줄에 if안에 let 설정해서 return하는 방식 괜찮나요 ??
> [CHORE] 방장, 참여자 둘 다 설정버튼으로 수정

- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailHalfModalController.swift
- close #45 
- 진행기간 설정에 오늘보다 이전 날짜는 선택 안되고 alert창을 띄웁니다
- 최대 7일까지 선택이 가능하게 구현했습니다
- 시작 날짜(첫 탭)를 선택하면 선택 가능한 부분은 흰색, 아닌 부분은 회색으로 사용자가 보기에 직관적으로 구현했습니다
- 시작과 끝 기간을 설정하면, 과거를 제외한 모든 일이 흰색으로 보여서 터치가 가능하도록 구현했습니다
- 301~313번째 줄 클로저를 이용한 더 짧은 코드로 변경이 가능한가요 ?? 가능한지 알려만 주세요 이제 막 클로저랑 친해지려 노력중이예요
- 제일 처음 들어왔을땐 과거를 제외한 모든 날짜에 터치 가능하게 표시해야해서 isFirstTap 함수로 처음인지 아닌지를 구분했는데, 두 시간을 비교하는 과정이 순탄치 않아서 boolean값으로 컨트롤 했어요 더 좋은 방법이 있을 것 같은데 아시면 알려주세요 !
- 시작과 끝기간을 설정하고 수정하려고 다시 탭하면 반짝하는 이펙트가 있는데 수정이 어렵네요 ..ㅠ
- 예를들어 시작일이 6월 15일이면 6월 22일 이후로는 설정이 안되는데 7월이 넘어가면 alert는 뜨지만 선택이 되요.. 이거도 수정이 쉽지않네요 ..
> [FEAT] 캘린더 기간 설정 기능 추가

- Manito/Manito/Screens/Detail-Wait/UIComponent/DetailHalfModalController.swift
- close #61
- 모달이 올라왔을때 처음 선택되어있는 기간을 누르면 선택 가능범위가 안뜨는 문제 해결
- 함수가 실행되는 순서상의 문제가 생겼는데, 이전 뷰에서 기간을 전달받는 식으로 코드를 짜서 isFirstTab이 필요없어짐
- 그에따라 문제가 해결됨
> [FIX] Calendar 날짜 선택 오류 수정

- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- close #115 
- 모달을 내릴 때 alert 표시했습니다.
- 제일 처음 수정하러 들어갔을 땐 기본으로 오늘로부터 5일 후 까지인데 그 상태에서 모달을 내렸을땐 "저장하시겠습니까??" 가 뜨고
- 시작일만 정하고 모달을 내렸을 땐 "폐기하시겠습니까??" 가 뜨고
- 시작과 끝날짜를 다 정하고도 모달을 내리면 "저장하시겠습니까??" 가 뜹니다.
- 해당 alert멘트가 괜찮은지 검토 부탁드립니다.
- `presentationControllerDidAttemptToDismissAlert` 이 함수 내부에서 guard와 if를 섞어서 사용하는데 괜찮은 방법인지 조언부탁드립니다.
> [FEAT] DetailEditView 모달 내릴때 alert 표시

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- close #122 
- "마니또 참가명단" 과 "함께하는 친구들"을 섞어 사용하고 있었는데 "함께하는 친구들"로 명칭을 통일했습니다.
> [CHORE] 함께하는 친구들로 명칭 통일

- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
- close #124 
- 마니또 시작 버튼 눌러서 시작 후 진행 화면이 떳을 때 뒤로가면 다시 대기중 화면으로 돌아가던 flow를 수정했습니다.
- 넘어가는 화면이 적절한가요 ?? 살짝 끊기는 것 처럼 보일수도 있을 것 같아서요 !
- GIF참고해주세요 !
- 1번 2번 어떤게 더 나은지 답변 부탁드립니다. 화면 전환 애니메이션 차이입니다 !
- 1번
- 2전
> [CHORE] 마니또 시작 후 대기방으로 돌아가는 flow 수정

- Manito/Manito/Global/Resource/Storyboards/DetailIng.storyboard
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
close #116 
마니띠를 눌렀을때 2초동안 보이고 다시 사라지는 애니메이션을 추가했습니당.
- 저는 마니띠를 manitoRealImageView 라고 줬는데 좀 더 제대로된 ... 좋은게 뭐가 있을까용..ㅎㅎ
- UIView의 애니메이션 클로저에서는 self를 약한 참조를 하지 않았는데 괜찮을까요? 
- 오토레이아웃이 하나 잘못 되어있어서 수정했습니다. 
https://user-images.githubusercontent.com/59243274/184150965-3442995a-2f35-41c8-9db5-d2f54bab95e3.mp4
> [FEAT] 마니띠 누르면 애니메이션 동작 추가

- Manito/Manito/Global/Extension/Notification+Extension.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #126 
- 시작날짜 변경에 따라 마니또 시작버튼이 활성화됩니다.
- 날짜 변경버튼을 누르면 Notification으로 알림을 줘서 함수를 실행시키는데 다른 방법이 있을까요 ?? 클로저를 사용하고 싶었는데 가능한지 잘 모르겠더라구요 ! 혹시 가능할까요...??
https://user-images.githubusercontent.com/78677571/184316160-09e48113-e402-48a2-b98e-1b4e3e0d7b56.mp4
> [FEAT] 날짜 변경에 따라 마니또 시작버튼 상태 변경

- Manito/Manito/Global/Resource/Storyboards/Interaction.storyboard
- Manito/Manito/Screens/Interaction/SelectManittoViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- close #117 
레버 스와이프 영역을 확장했습니다.
Swipe Background View를 생성하고 그 위에 레버와 레버 라벨을 올렸습니다.
- Swipe Background View는 safe area로 영역을 잡았기 때문에 화면 전체에서 스와이프가 가능합니다.
> [CHOER] 레버 스와이프 영역 확장

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #127 
- 시작 날짜가 지났을 때 alert이 표시되고 모달이 올라왔을 때 날짜를 수정하지 않고 dismiss 후 방 정보 수정을 누르면 날짜가 기존 설정날짜로 되있어서 깨지는 현상이 발생하는 걸 해결했습니다.
- 방정보수정 UIAction 클로저에 다 때려박힌 느낌인데 괜찮을까요 ..??
https://user-images.githubusercontent.com/78677571/184321455-53c459f1-98e0-4ffb-8612-ef678abe82aa.mp4
> [FEAT] 시작날짜 지났을 때 방 정보 변경시 default 날짜 추가

- Manito/Manito/Screens/CreateRoom/Component/CheckRoomView.swift
- Manito/Manito/Screens/CreateRoom/Component/InputDateView.swift
- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- close #146 
- 방 생성뷰에서 시작날짜와 끝나는 날짜를 선택할 수 있습니다.
- 기존에 구현해둔 캘린더를 사용했습니다.
- 그 과정에서 캘린더의 기능을 조금 추가했습니다.
- 스누피와 듀나의 조언대로 calendarView의 변수에 private를 주고 함수를 만들어서 내부 변수에 접근하도록 만들었습니다. 함수명에 get을 사용했는데 컨벤션에 혹시 어긋날까요 ??
https://user-images.githubusercontent.com/78677571/186101241-8d248c2f-4030-4d85-852f-ad8152f630d8.mp4
> [FEAT] 방 생성뷰 캘린더 기능 추가

- Manito/Manito/Screens/Letter/Cell/LetterCollectionViewCell.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Letter/UIComponent/LetterHeaderView.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- close #142 
- Letter View Controller Spacing 변경
- Letter View에서 Collection View의 레이아웃이 자꾸 무너지는 문제가 생겨서(prepareForReuse 때문) 이 부분을 수정했습니다.
- CollectionView Cell의 높이를 미리 계산해서 정하는 방식으로 진행했습니다.
- Spacing를 20으로 변경했습니다.
- Cell의 높이가 동적으로 바뀌는 데 전에는 `preferredLayoutAttributesFitting`메소드를 써서 해당 부분을 구현했었습니다. 하지만 메소드가 Layout를 처음 한 번만 잡아주어서 Reuse될 때 높이가 다 망가지더라구요. 그 부분을 고치기 위해서 CollectionViewFlowLayoutDelegate 안에 있는 itemSize 부분에서 매번 각 셀의 높이를 잡아줄 수 있도록 구현했습니다. 지금은 잘 구동됩니다.
https://user-images.githubusercontent.com/55099365/186290435-c7bba155-dc23-47ac-9be2-acbe560320e7.mp4
> [FEAT] Letter View Spacing 변경 및 dynamic height 오류 해결

- Manito/Manito/Global/Extension/Notification+Extension.swift
- Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- close #135 
- 캐릭터 선택하기 뷰 추가
- 일부 팝업을, 네비게이션컨트롤러로 수정 (방 생성하기 처럼!)
- 방 정보 확인 후, 'Yes'를 누르면, 팝업 닫고, 캐릭터 선택화면으로 넘어감
https://user-images.githubusercontent.com/57849386/184496704-d04968e4-0eda-4f3d-8b58-2ef54baf3cb3.mp4
> [FEAT] 캐릭터 선택 뷰 추가, 팝업 에러 해결

- Manito/Manito/Global/Extension/Notification+Extension.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- close #144 
- 대기방에서 최대 인원이랑 UISlider랑 연결이 안되어있었고, 값을 변경해도 반영이 되지 않은 문데를 해결했습니다.
- 방 정보 수정에서 현재 참가한 인원보다 더 적게 최대 인원을 설정할 때 alert 표시를 했습니다
++ API연결할 때 방 정보 수정할 때 찰나에 현재인원이 추가되진 않았는지 확인하는 작업이 필요해 보입니다.
DetailEditViewController에 265~280 번째 줄에 중복되는 코드가 있는데 하나의 함수로 빼는게 좋을까요 ??
https://user-images.githubusercontent.com/78677571/185624868-5049fb9e-a28b-4a41-9af9-49008a02c77d.mp4
> [FEAT] 최대 인원 Slider반영, 현재 인원보다적게 설정할 때 alert표시

- Manito/Manito/Global/Resource/Storyboards/Letter.storyboard
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- close #176 
끝난 방이라면 ViewController로 들어올 때 Type으로 String값을 받아서 하단 쪽지 생성 뷰로 이어지는 버튼이 생성되지 않도록 구현했습니다.
- "POST"라는 단어가 들어오면 하단 쪽지 생성 뷰로 넘어가는 버튼이 레이아웃을 잡지 않도록 했습니다.
- `lazy var`로 설정했습니다.
detail-ing에서 연결해서 밖 뷰는 끝난 상태가 아닙니다. 테스트한 것!
https://user-images.githubusercontent.com/55099365/187695067-f279e317-9194-47f4-af79-348cbd1fd1ae.MP4
> [FEAT] 끝난 방이라면 쪽지 전송 뷰로 이동하지 못하도록 구현 완료

- Manito/Manito/Network/Models/Room.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #199 
- 마니또 시작가능 조건이 날짜가 오늘일때로 설정이 되어있었는데, 오늘일 때 && 최소 5명이상일 때 로 변경했습니다.
- 최대 인원이 api에서 값이 리턴되지 않아서 작업 못했던 부분을 연결 작업했습니다.
https://user-images.githubusercontent.com/78677571/188566081-57e5a356-e09c-4743-8e98-634f3a7472ba.mp4
> [FEAT] 마니또 시작가능 조건 적용, 최대 인원 API반영

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Extension/UserDefault+Extension.swift
- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Network/API/SettingAPI.swift
- Manito/Manito/Network/EndPoint/SettingEndPoint.swift
- Manito/Manito/Network/Models/NicknameDTO.swift
- Manito/Manito/Network/Protocol/SettingProtocol.swift
- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- close #201
- 닉네임을 저장하는 userDefault를 편하게 쓰려고 익스텐션 했습니다.
- 닉네임 변경때 API 연결해서 보내는거 확인했습니다.
- 애플 로그인 까지 머지되면 듀나의 유저디폴트 관리로 넘어가겠습니다.
> [FEAT] 닉네임 변경하기 유저디폴트 관리, 서버에 보내기

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- close #219 
- 방 삭제시에 바로 뒤로가져서 삭제가 안된 main이 불리는 걸 방지하고자 0.5초 딜레이를 추가했습니다.
https://user-images.githubusercontent.com/78677571/189304189-ceb82c80-09e9-4eed-b429-d54107513e00.mp4
> [FEAT] 방 삭제시 딜레이 추가

- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
- resolve #232 
TextField가 최대 카운트 이후에 타이핑을 하면 글자가 이상하게 먹히는 문제를 해결했습니다.
- Textfield가 다 차고 나면 글씨를 자동으로 지웁니다.
- 자동으로 지우는 코드가 조금 달그락 거려서 고것이 문제긴하지만 전과 같은 문제는 없습니다.
```swift
DispatchQueue.main.asyncAfter(deadline: when) {
self.roomsNameTextField.text = String(fixedText)
self.setCounter(count: textField.text?.count ?? 0)
}
```
https://user-images.githubusercontent.com/55099365/189545261-35dc4424-db1c-4821-83c0-b33f4467e41d.mp4
> [FIX] TextField 최대 카운트 이후로 생기는 문제 해결

- Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
- close #235
- 방 생성하기 와 케릭터 선택뷰 사이의 버튼 위치가 달랐습니다.
- 방 생성하기에서 버튼의 위치가 safeArea에서부터가 아니라 바텀으로 부터 잡혀있었습니다. 
https://user-images.githubusercontent.com/59243274/189597482-40293f26-4607-470b-9c8e-5907ea582be2.mp4
> [CHORE] 버튼 높이가 달랐던거 수정

- Manito/Manito/Global/Extension/Date+Extension.swift
- Manito/Manito/Global/Extension/String+Extension.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- close #228 
- 마니또 공개버튼이 당일 && 당일 09:00 이후에 버튼이 활성화 되게 변경했습니다.
- Extension에 추가했습니당
> [FEAT] 마니또 공개버튼 종료일 9시이후 활성화되게 추가

- Manito/Manito/Network/API/LetterAPI.swift
- Manito/Manito/Network/API/RoomAPI.swift
- Manito/Manito/Network/Protocol/LetterProtocol.swift
- Manito/Manito/Network/Protocol/RoomProtocol.swift
- Manito/Manito/Network/Service/APIService.swift
- Manito/Manito/Network/Service/Requestable.swift
- Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- close #245 
Header Code에 있는 값들을 return할 수 있도록 request를 수정해서 구현했습니다.
- StatusCode를 return하는 `request`
- 쪽지 보내기 부분에서 해당 방식을 사용했습니다.
```swift
func request(_ request: NetworkRequest) async throws -> Int {
let (_, httpResponse) = try await requestDataToUrl(request)
switch httpResponse.statusCode {
case (200..<300):
return httpResponse.statusCode
case (300..<500):
throw NetworkError.clientError(message: httpResponse.statusCode.description)
default:
throw NetworkError.serverError
}
}
```
<br/>
- Location를 return하는 `request`
- 방 생성 부분에서 해당 방식을 사용했습니다.
```swift 
func requestCreateRoom(_ request: NetworkRequest) async throws -> Int? {
let (_, httpResponse) = try await requestDataToUrl(request)
switch httpResponse.statusCode {
case (200..<300):
let responseUrl = …
```
> [FEAT] Header Code에 있는 값들을 return할 수 있도록 request 구현

- Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
- Manito/Manito/Screens/CreateRoom/Component/InputNameView.swift
- Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
- Manito/Manito/Screens/Setting/ChangeNickNameViewController.swift
현재 텍스트필드에 텍스트를 입력하면 달그락달그락 거리는 문제가 있습니다. 그 버그를 해결하는 PR입니다.
현재 0.01초 이후에 실행되도록 보장하는 코드가 있습니다. 
이코드 때문에 달그락 거리는 버그가 있는 모습으로 구현되었는데 0.01초 이후에 실행되도록 보장하지 않아도 잘 실행되기 때문에 그 부분의 코드를 삭제했습니다.
- 텍스트 필드가 있는 코드들은 다 수정했습니다.
- 버그 해결
- 텍스트 필드가 현재 로그인 후에는 방생성, 방참여, 닉네임 수정 시 있습니다. 그 쪽으로 와서 최대글자를 입력해보시면 됩니다
- 날먹 PR입니다. 화이팅!
- close #324
> [FIX] 텍스트 필드 달그락 거리는 버그 해결

- Manito/Manito/Screens/Letter/LetterViewController.swift
https://user-images.githubusercontent.com/78677571/199732754-7fd065d4-1766-4097-a346-c1c0f2be8e65.mp4
위의 영상에서 보면 쪽지함 뷰에서 가이드 버튼을 누르면 내용이 잘 표시됩니다. 뒤로가기를 해도 잘 사라지고, 한번 더 눌러도 잘 사라지고, 세그먼트를 이동해도 잘 사라집니다. 하지만 사라지지 않는 한 방법이 있었습니다.
왼쪽으로 쓸어서 dismiss를 하게되면 해당 뷰가 사라지지 않고 둥둥 떠있는 현상이 발생했습니다. 어딜가나 계속 떠있고, 앱을 껐다 켜는 것 말고는 사라지게 하는 방법이 없었습니다. 
이 문제를 해결하기 위한 PR입니다 ^_______^
해당 이미지 view를 viewController의 life cycle중 하나인 `viewWillDisappear` 부분에서 `isHidden` 처리시켜 주었습니다.
feature/331-letter-info-bugfix 브랜치로 오셔서 실행 시키시고, 진행중이나 완료방의 쪽지함으로 가시면 됩니다.
이후 오른쪽 위의 가이드 버튼을 누르고 뒤로갔을 때 잘 사라지는지 확인 해주시면 됩니다.
viewWillDisappear 부분을 주석처리했을때, 가이드 뷰가 떠있는 상태로 왼쪽으로 쓸어서 뒤로가기를 한다면 해당 버그가 발생될 것이고, 주석을 해제하면 가이드 뷰가 잘 사라질겁니다.
https://user-images.githubusercontent.com/78677571/199733941-08923a8b-7268-44e9-af6a-a6e0b88c38fd.mp4 …
> [FIX] LetterView Guide View 사라지지 않는 문제를 해결했습니다.

- Manito/Manito/Global/Supports/AppDelegate.swift
- Manito/Manito/Global/Supports/SceneDelegate.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
기존 PR(https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/353) 에서 쪽지가 왔을 때 푸시알림 기능을 구현했습니다. 하지만 푸시알림을 눌러도 그냥 앱에만 들어가지지 어떤 방에서 쪽지가 왔는지는 알 수 없습니다. 그 문제를 해결하기 위해 해당 PR을 작성하게 되었습니다 !
마니또로부터 쪽지가 왔을 때 푸시알림이 옵니다. 그 알림을 눌렀을 때 해당 방으로 바로 이동하고, 쪽지함 화면까지 이동합니다. 
대뜸 쪽지함까지 갔더니 
이 화면이 떠서 저 조차도 당황스럽더라구요. 이 문제가 발생하는 이유가, 쪽지함의 Segment Controll의 기본값이 내가 마니띠에게 보낸 쪽지를 보여주는 화면이라 생긴 문제였습니다. 그래서 이 Segment를 마니띠로부터 시작하게끔 코드를 추가했습니다.
마니또에게 쪽지를 요청하고, 푸시알림을 눌러서 앱에 들어가보세요 (애니또 릴리즈 톡방에 방을 만들어서 요청하는게 편할겁니다.)
https://user-images.githubusercontent.com/78677571/211328725-624a1f4c-53fd-46c5-b498-1f5509435b31.MP4
view들이 너무 독립적이지 못하고 어디 한 쪽에 의존하고 있어서 꽤나 애를 먹었습니다.
1. 서버 통신 횟수를 줄이기 위해 클라쪽에서 데이터들을 전달하다보니 문제가 생겼습니다. 
예시로 `LetterViewController`의 `mission`이란 변수였는데요, 진행중인방 View(DetailIngCodebaseViewController) -> …
> [FEAT] 푸시알림을 눌렀을 때 해당 방의 쪽지뷰로 이동 기능 구현

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Manito/Manito/Screens/Main/Cell/ManitoRoomCollectionCell.swift
- Manito/Manito/Screens/Main/MainViewController.swift
- Manito/Manito/Screens/Main/UIComponent/CommonMissionView.swift
메인뷰에서 스켈레톤으로 방목록을 로드하는 기능을 추가하였습니다.
`SkeletonView` 라이브러리를 먼저 설치하였습니다.
그리고 `MainViewController`에 skeletonAnimation를 선언해주었습니다.
`private let skeletonAnimation = SkeletonAnimationBuilder().makeSlidingAnimation(withDirection: .leftRight)`
애니메이션 방향은`leftRight`, 왼쪽에서 오른쪽으로 설정하여, 로딩을 기다리는 시간을 덜 지루하게 하였습니다.
(cf. 왼쪽에서 오른쪽으로 진행되는 애니메이션의 로딩 체감 시간이 가장 짧다고 합니다.)
그리고 방목록 컬렉션뷰에 스켈레톤 애니메이션을 적용시키기 위해, 스켈레톤 컬렉션뷰를 따로 만들어주었습니다.
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/blob/e2a934dd2b0be75539c6e76803e6632046ce3971/Manito/Manito/Screens/Main/MainViewController.swift#L339-L348
스켈레톤을 적용하고자 하는 요소에 `isSkeleton = true`를 해주면, 스켈레톤 애니메이션이 적용되게 됩니다.
SkeletonView 은 재귀적이기 때문에 부모뷰에 true값을 주어야 자식뷰에도 적용됩니다.
기존 `MainViewController`에서 CommisionView와 터미널 이미지가 따로 있는 것을 확인하여, CommisionView안으로 이미지를 넣고, …
> [FEAT] 메인뷰 방목록 로드에 스켈레톤 적용

- Manito/Manito/Screens/Interaction/OpenManittoPopupViewController.swift
호야가 제보해준 마니또가 누군지 알 수 없는 현상에 대해 수정했습니다 !
- 사이즈에 맞춰 폰트 크기 조절
- 좌우 inset값 10 -> 24로 수정
전 마니또 공개까지 가기 번거로워서 SceneDelegate 에서 rootView를 아래와 같이 변경 후 실행했습니다.
```swift
let testViewController = OpenManittoPopupViewController()
window.rootViewController = testViewController
```
사진으로 보여드리자면 
|iPhone 13 mini|iPhone 14 Pro|
|---|---|
|<img src="https://user-images.githubusercontent.com/78677571/220115069-ed8a7b40-9eec-4a6e-bd69-20f7955033c8.gif" width="300">|<img src="https://user-images.githubusercontent.com/78677571/220115052-7686a3c8-1edc-47c4-ba8c-880d3612cda4.gif" width="300">|
기존의 코드에서 사이즈에 맞게 폰트를 줄이는 코드만 추가하니까 아래 사진과 같이 좌우를 초과하는 문제가 있어서 
|iPhone 13 mini|iPhone 14 Pro|
|---|---|
|<img src="https://user-images.githubusercontent.com/78677571/220115667-c5a21c3f-e8af-426c-8752-23d8ee3964f6.png" …
> [FIX] 마니또 공개 텍스트 잘림 현상 해결

- Manito/Manito/Global/Extension/UIViewController+Extension.swift
- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Screens/Letter/UIComponent/CreateLetterPhotoView.swift
* #379 PR을 진행하면서 발견한 카메라 권한, Picker Delegate 코드 관련 문제들을 해결했습니다.
⓵ 현재 카메라를 통해서 사진을 가져올 때, 카메라에 대한 접근 권한이 없으면 따로 alert가 뜨지 않고 검은 화면으로 넘어갑니다. 라이브러리 접근 권한이 없을 때 설정으로 보내주는 것처럼 카메라도 접근 권한이 없으면 설정으로 보내는 작업을 하려고 합니다.
⓶ PHPickerController Delegate 함수 내부가 load에 대한 에러 처리라던지, ui부분과 image를 load하는 함수들이 섞여 있어서 읽기가 쉽지 않은거 같아서 분리를 해보려고 합니다.
총 두 가지 권한을 확인했습니다. ⓵ SoureType(카메라)이 사용 가능한 상태인지 ⓶ 현재 Access가 가능한지 를 확인했습니다.
```swift
private func checkImagePickerControllerAccessRight() {
guard UIImagePickerController.isSourceTypeAvailable(.camera) else {
self.viewController?.makeAlert(title: "오류", message: "해당 기기에서 카메라를 사용할 수 없습니다.")
return
}
AVCaptureDevice.requestAccess(for: .video) { [weak self] granted in
DispatchQueue.main.async {
granted ? self?.imagePickerControllerDidShow() : self?.openSettings()
}
}
}
``` …
> [FEAT] 카메라 권한 관련 코드 추가 및 Picker Delegate 코드 수정

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Error/Screens/Letter/LetterImageError.swift
- Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
- Manito/Manito/Screens/Letter/LetterImageViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Letter/View/LetterImageView.swift
LetterImageViewController는 서버 연결이 따로 없는 UIViewController입니다. Server API와의 연결이 없기 때문에 분리할 Model 관련 메소드나 변수도 없어서 View를 분리해봤습니다.
*Photo 라이브러리를 사용해서 사진을 저장하는 경우같은 Usecase가 나타나긴 해서 후에 이 부분을 따로 ViewModel로 뺄 수 있지 않을까 싶긴 한데, MVVM에 대한 이해도를 더 높이고 나서 생각해보겠습니다.
<br>
**⓵ UI Component를 UIView 내부로 넣었습니다.**
UI Component와 UI Component 관련 메소드들을 UIView 내부로 넣었습니다. UIView는 UIViewController의 view로 설정을 했습니다.
```swift
override func loadView() {
self.view = self.letterImageView
}
```
**⓶ UIAction에 대한 부분을 Delegate Pattern를 사용해서 UIViewController가 대신 하도록 구현했습니다.**
UIAction 내부에서 View 이외의 값을 변경해야 한다거나(서버 연결, 데이터 변경, 다른 뷰 변경), UIViewController에서 Action를 도와줘야 할 시(UIViewController에서 만들어서 사용해야하는 Function) Protocol로 해당 메서드들을 만들고 UIViewController에서 이를 conform해서 사용하도록 구현했습니다.
```swift
protocol LetterImageViewDelegate: …
```
> [REFACTOR] LetterImageViewController에서 View를 분리했습니다.

- Manito/Manito/Screens/Letter/CreateLetterViewController.swift
- Manito/Manito/Screens/Letter/View/CreateLetterView.swift
쪽지가 전송되는 동안 버튼이 비활성화되지 않아서 중복으로 보내기가 가능해집니다.
사용자가 불편함을 느낄 거 같아 이 부분을 수정했습니다.
Sending 변수는 보내는 중일때 true로 설정해주면 보내기 버튼의 isEnabled를 false로 설정해줍니다.
반대로 보내기가 실패하고 나서 Sending 변수를 false로 설정해주면 버튼의 isEnabled를 true로 설정해줍니다.
sendButton의 isEnabled에 직접적으로 true, false 값을 넣어주는게 과연 좋은걸까 라고 생각이 들어서 Sending이라는 변수를 따로 만들어서 사용했습니다. 
feature/406-sendbutton-disable 브랜치에서 빌드 돌려보시면 확인하실 수 있습니다. 
일요일까지 한다고 했는데 화요일에 했네요.. 늦은 PR 죄송합니다. 🙇‍♂️
* 쪽지를 보내고 연타를 하고 있었습니다. 버튼이 비활성화되어서 쪽지가 보내지지 않는걸 보실 수 있습니다.
https://user-images.githubusercontent.com/55099365/224872245-f9198d11-37fc-4a30-a58e-066fbe47d6c1.mp4
* 쪽지 보내기가 실패했을 때 화면입니다. 실패했을 시에 버튼이 활성화되는걸 보실 수 있습니다.
https://user-images.githubusercontent.com/55099365/224872362-979122bf-d8d8-4d98-ac84-979d0ef1bd5d.mp4
- close #406
> [FEAT] 쪽지가 전송되는 동안은 보내기 버튼이 비활성화 되도록 구현했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Base/BaseViewController.swift
- Manito/Manito/Global/Literal/ImageLiteral.swift
- Manito/Manito/Global/Literal/TextLiteral.swift
- Manito/Manito/Global/UIComponent/GuideView.swift
- Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
- Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
- Manito/Manito/Screens/Letter/LetterViewController.swift
- Manito/Manito/Screens/Main/MainViewController.swift
GuideView가 BaseViewController 내부에 들어가 있어서 View 분리를 진행할 때 어려움이 있습니다. GuideView가 BaseViewController 내부에 메소드와 변수들을 만들어둬서 BaseViewController, UIViewController와의 의존성이 높습니다.
따라서 GuideView를 따로 UIView로 떼어내어 의존도를 낮춥니다.
일단 BaseViewController가 가지고 있는 UI Component들과 메소드들을 분리해냈습니다. 그리고 type(Screen) 별로 다른 Configuration, Layout 등을 가질 수 있도록 했습니다.
```swift
enum GuideType: String {
case letter
case main
case detailing
}
```
총 세가지의 타입을 만들었습니다. 타입은 Screen별로 나눴고 letter, main, detailing에서만 Guide를 사용하기 때문에 타입은 세가지만 존재합니다. 각각은 사용하는 메소드가 조금씩 다릅니다.
* 초록색 : 모든 Type에서 사용되는 함수입니다. GuideButton를 눌렀을 때 일어나는 Action과 내부 Configuration이 image, text를 제외하고는 동일하기 때문에 init() 메소드 내부에서 호출되도록 했습니다.
* 다른색 : 각각의 Type에서 부르는 메소드 입니다. 
* `setupGuideViewLayout`
- Main, Detailing은 일반 View(UIViewController의 View)에 GuideView를 얹고서 사용합니다. …
> [REFACTOR] GuideView를 BaseViewController에서 분리했습니다.

- Manito/Manito/Screens/Interaction/OpenManittoPopupViewController.swift
- Manito/Manito/Screens/Interaction/OpenManittoViewController.swift
마니또 공개 화면에서 XR 기종에서 레이아웃이 깨지는 문제가 발생하여 이를 해결했습니다.
정해진 width 값이 소수점을 가지고 있어서 결과적으로 전체 화면보다 더 큰 값을 가지게 되어 collectionView가 무너졌던 거 같습니다.
XR 기종에서 cell width 값을 확인하면 이렇게 찍힙니다.
해당 interitemspacing, insetspacing, cell width를 더하면 전체 width 사이즈인 414를 넘게 됩니다. 따라서 floor로 감싸서 내림값을 가지도록 수정했습니다.
| iPhone SE(3rd) | iPhone 12 mini | iPhone 14 Pro Max |
|--------|--------|--------|
| <img src="https://user-images.githubusercontent.com/55099365/226106577-f1d3fec4-d399-4741-a581-57edaa57fa36.png" width="350"> |<img src="https://user-images.githubusercontent.com/55099365/226106600-b88f575f-a9e9-4a02-8904-27f987211b9b.png" width="350">  |<img src="https://user-images.githubusercontent.com/55099365/226106618-9f438ac8-3e45-4713-a4b7-c99daa71e6cf.png" width="350"> |
iPhone XR …
> [FIX] 마니또 공개 화면에서 레이아웃이 깨지는 문제를 해결했습니다.

- Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
- Manito/Manito/Screens/Interaction/OpenManittoPopupViewController.swift
백로그에 적혀있던 마니또 공개 화면에서 생기는 문제들을 해결했습니다.
마니또 공개 화면에서 내용을 본 후에 메인 화면이 아닌 디테일-ing 화면으로 이동하도록 수정했습니다.
```swift
guard let parentViewController = self?.presentingViewController else { return }
self?.dismiss(animated: false, completion: {
parentViewController.dismiss(animated: false)
})
```
이전에는 RootVC로 이동하도록 되어있어서 이를 수정했습니다.
팝업 뷰를 dismiss하고, 마니또 공개 애니메이션(CollectionView 형태)을 dismiss하는 식으로 변경했습니다.
마니또 공개 화면은 present 기능을 통해서 진행됩니다. 따라서 뒤로가기 버튼이 나타날 수 없습니다.
하지만 코드가 navigationController에서 push하는 방식으로 짜여져있어서 생기는 문제점이었습니다.
이를 present하는 방식으로 다시 수정했습니다.
```swift
let viewController = OpenManittoViewController(roomId: roomId)
viewController.modalTransitionStyle = .crossDissolve
viewController.modalPresentationStyle = .fullScreen
self?.present(viewController, animated: true)
```
해당 브랜치로 이동 후에 진행해주세요.
**[마니또 …
> [CHORE] 마니또 공개 화면에서 생기는 문제들을 해결했습니다.

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
View를 분리하던 #444 PR에서 해당 버그를 발생시킨채 머지가 되었습니다.
해당 두 버그를 해결하는 PR입니다.
1. 초대코드 복사 버튼을 눌러도 안뜨는 버그 해결
2. 방 생성 후 초대 코드 뷰가 안뜨던 버그 해결
(초대코드 뷰란?)
1번 버그는 단지 `setupCopyButton`함수를 호출하지 않아서 생기는 문제였기에 호출해줌으로써 해결했습니다.
2번 버그는 방 생성 완료시에 Notification으로 알림을 보내는데 제가 View를 분리하면서 Notification을 받는 코드를 삭제했었습니다... 그래서 해당 코드를 다시 추가해서 해결했습니다 ^__________^
feature/469-detailwait-invitationcode-fix 브랜치로 오셔서
1. 방을 만들었을 때 초대코드 뷰가 잘 뜨는지,
2. 대기방에서 초대코드 복사 버튼을 눌렀을 때 토스트뷰가 뜨면서 초대코드가 잘 복사되는지
를 확인해주시면 감사하겠습니다 ^___________^
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/78677571/2d88e079-7b70-4d67-ac81-01e03f03c11b
아무리 꼼꼼하게 확인한다 해도 놓치는 버그가 항상 생기군요... 이걸 미리 캐치할 수 있는 UI테스트를 만들 수 있다면 좋을 것 같네요! 열심히 해보겠습니다.
- close #469
> [BUGFIX] 대기중 방의 초대코드 관련 버그를 해결했습니다.

- Manito/Manito/Network/Models/Request/RoomDTO.swift
마니또 방을 생성하거나, 참가할 경우 캐릭터를 선택하게 되는데 아무리 선택해도 결국 DB에 0으로 들어가는 문제가 있었습니다.
해당 버그를 해결하는 PR입니다.
단순히 코딩키를 추가했습니다.
`feature/471-character-index-fix` 브랜치로 오셔서 방을 만드시거나, 참가하시고 포스트맨을 통해
`api/v1/rooms/:roomId/participants` 주소를 통해 호출하시면 조회 가능합니다!
물론 헤더에 Bearer 토큰을 넣어주셔야 합니다!
현재 대기중인 방에서 함께하는 친구들을 확인할 수 없어서, postman을 통해 확인하였습니다.
(듀나가 만들어 주신 방)
(제가 만든 방)
현재 버그가 발생하는 상황을 보면
저랑 호야랑 듀나는 0번 인덱스의 캐릭터가 선택되지만 리비의 캐릭터는 제대로 선택되는 걸 볼 수 있습니다.
이를통해 v1.5.0 이후 개발 과정에서 문제가 생긴걸 인지했습니다.
현재 서버 명세를 보게되면 인덱스 값을 `colorIdx`라는 이름의 변수로 받는걸 알 수 있습니다.
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/commit/b6d3ba8b39e446f0262febb1528279846f8c0873
하지만 지난 커밋 중 변수명을 조금 더 iOS스럽게 변경하는 과정에서 예상치 못한 버그가 시작된 것 이었습니다.
해당 문제는 CodingKey를 추가함으로써 간편하게 해결 하였습니다. 
드는 생각으론.. 이 모든 것을 테스트 코드로 확인이 가능하다면 엄청날 것 같네요.. 쉽진 않겠지만요..ㅎㅎ
- …
> [FIX] 캐릭터 선택시에 0번 인덱스로 들어가는 버그를 해결했습니다.

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Global/Extension/URLInfo+Extension.swift
- Manito/Manito/Global/Literal/URLInfo.plist
- Manito/Manito/Global/Literal/URLLiteral.swift
회원탈퇴 기능을 추가하기 이전에 해당 작업이 선행되었어야 했습니다. 
그 이유는 현재 Production 서버로만 모든 걸 사용하고 있는데, 허클베리가 개발서버와 배포서버를 나눠주셨고 회원탈퇴 기능은 개발서버에만 우선적으로 배포되어있기 때문입니다.
URL을 숨겨야하는 이유는 무엇인가?? 에 대한 답변을 드리자면, 누군가 악의적인 마음을 가지고 공격을 한다고 했을때 전혀 대비가 되어있지 않기 때문입니다. 애초에 처음 올릴 때 부터 해당 값을 숨기고 사용했어야 했는데.. 늦게나마 해당 값을 숨기고자 합니다.
URLInfo.plist 파일을 만들었습니다.
해당 파일에 URL 값을 개인적으로 추가해서 사용하시면 됩니다.
아닙니다. 터미널에
`git update-index --skip-worktree Manito/Manito/Global/Literal/URLInfo.plist`
해당 코드를 입력하면 더이상 git이 추적을 하지 않게 됩니다.
**설정 전**
**설정 후**
URLInfo.plist의 값을 사용하는 URL주소로 수정했음에도 git이 추적하지 않는 모습입니다. 
`feature/477-hide-url` 브랜치로 오셔서 
위처럼 수정하시고 테스트 부탁드립니다. 현재 저희는 Production URL로 모든것이 연결되어 있습니다.
URL 주소는 저희 노션에 `기밀사항` 페이지에 있습니다.
잘 모르겠다면 언제든 연락주십셔 ^________^
Q. gitignore를 사용하면 더 편하게 숨길 수 있지 않나요??
A. 네 맞습니다. 애초에 gitignore를 추가하고 모두가 같은 세팅으로 진행했다면 문제없이 숨길 …
> [CHORE] URL 숨기기 작업을 위한 PR입니다.

- Manito/Manito/Screens/Letter/Views/UIComponents/LetterHeaderView.swift
- Manito/Manito/Screens/Letter/Views/Views/LetterView.swift
LetterViewController에서 LetterView와 LetterHeaderView가 메모리에서 해제되지 않는 문제가 발생했습니다.
LetterView와 LetterHeaderView만 계속 메모리에서 해제되지 않아서 HeaderView에 문제가 있다고 판단하여 HeaderView관련 코드를 주석처리하고 빌드를 해보니깐 LetterView가 제대로 메모리 해제되는걸 확인했습니다.
`[weak self]` 누락된 부분을 열심히 찾아본 결과, `LetterView`안에 있는 `createLayout` 메서드에서 `[weak self]` 누락을 확인했고, 해당 부분이 Header를 설정하는 `sectionHeader` 메서드에 self를 써주는 부분이라서 문제가 생긴 거 같습니다.
`[weak self]`를 써주고 나니 메모리 해제가 잘 되는걸 확인할 수 있습니다.
메모리 릭 관련 테스트를 해보고 싶으시면 빌드 런하는 아이콘을 꾹 누르면 Profile로 변경할 수 있습니다.
Profile로 빌드하시면 Instrument가 뜨는데, 거기서 `Leaks`를 선택하시고, Leaks 화면에서 녹화 버튼을 누르면 Memory Leak이 발생하는지 확인하실 수 있습니다.
표에 있는 `Persistent(#)`는 메모리에 계속 남아있는 클래스의 갯수이고, `Transient`는 해제된 클래스의 갯수입니다. 따라서, `Persistent`가 1를 초과하면 안됩니다. 그런 식으로 봐주시면 됩니다.🙇‍♂️
CreateLetterView에서 현재 쪽지가 안보내지는 문제가 있습니다.
~417 에러 코드가 뜨는데 이유를 …
> [FIX] LetterViewController 부분에서 발생하는 메모리 릭 문제를 해결했습니다.

- Manito/Manito/Screens/ChooseCharacter/View/ChooseCharacterView.swift
- Manito/Manito/Screens/CreateRoom/UIComponent/CharacterCollectionView.swift
방 생성시에는 문제가 없는데, 방 참여할 때 캐릭터의 인덱스가 항상 0번으로 고정되는 문제가 있었습니다.
위 사진은 호야가 배포 서버에 만들어준 방입니다.
6번째 캐릭터(인덱스 5번)을 선택하고 들어가도
0번으로 선택되어있는 문제가 있었습니다.
문제는 삭제예정이라 적어주셨던 `characterIndex = 0`의 값을 사용하고 있었기 때문입니다. 바로 아래 해당값을 스트림으로 변경해주셨지만 해당 변수를 삭제하지 않고 그대로 사용중이었습니다.
1. 문제의 `characterIndex`값을 삭제했습니다
2. `PassthroughSubject`로 만들었던 스트림을 `CurrentValueSubject`로 변경함으로써 초기값을 설정할 수 있었고, 사용하는 부분에서 .value를 통해 Int값에 접근할 수 있었습니다.
해당 브랜치로 오셔서 방 참가를 해보시면 됩니다.
배포 서버 초대코드는 `KTBQ2B` 입니다. 방 id는 268번 입니다. 포스트맨에 `rooms/268/participants` API로 조회해보시면 됩니다!
개발 서버 초대코드는 `20QBFT` 입니다. 방 id는 340번 입니다.
각각의 스트림으로 분리되어 있어서 그런지 굉장히 조금만 수정해도 문제가 해결되네요!
아주 좋아요 ^__________^
- close #525
> [CHORE] 방 참여시 캐릭터 인덱스가 설정 안되는 문제를 수정했습니다.

- Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
- Manito/Manito/Screens/ParticipateRoom/View/ParticipationRoomDetailsView.swift
- Manito/Modules/MTResource/MTResource/ColorSet.swift
프레임워크로 분리한 ColorSet의 노란색이 적용되지 않는 문제가 있었습니다.
기존 사용하던 UIColor+Extension에 yellow가 있었는데 해당 Extension이 프레임워크 위치로 옮겨지면서 해당 문제가 발생한 것 같습니다.
UIColor.yellow라고 사용했을때 우선순위가 저희가 프레임워크로 분리한 yellow보단 내장되어있는 yellow의 우선순위가 더 높았던 것 같습니다.
해당 문제를 해결하기 위한 PR입니다.
yellow라고 네이밍 되어있던걸 yellow001로 수정했습니다.
현재 브랜치로 오셔서
1. 메인 화면에서 방 생성하기 아이콘 배경색이 제대로 들어갔는지 확인
2. 방 참가하기 했을 때 YES NO 버튼 색이 제대로 들어갔는지 확인
부탁드립니다!
프레임워크로 분리했을때의 우선순위 변경이 생기는게 신기하고 재밌네요! ^___________^
- close #537
> [CHORE] ColorSet의 yellow네이밍을 수정합니다.

- Manito/Manito/Data/Network/Foundation/Key+Extension.swift
- Manito/Manito/Util/Literal/URLLiteral.swift
MemoryVC에서 인스타그램 공유가 안되는 문제가 발견되어 해당 문제를 해결했습니다.
자세한 작업 내용은 블로그에 적어뒀습니다. 궁금하신 분들은 하단 링크로 들어가서 보시면 됩니다.
- https://yoonah-dev.oopy.io/eb077683-4278-411c-85a3-bc339f14232f
인스타그램 공유가 안되는 문제는 **2023년 1월부터 바뀐 Meta 정책에 의해서 Meta Developer에서 앱 ID를 부여받은 앱에 한해서만 인스타 공유가 가능**해졌기 때문입니다.
따라서, Meta Developer 페이지에 애니또 앱을 생성하고 앱 ID를 받았습니다.
실제로 수정된 코드는 인스타그램 스토리 관련 부분 코드밖에 없어서 PR을 보기에 어려움은 없으실 겁니다.
```swift
static let instagram: String = "instagram-stories://share?source_application=\(Bundle.main.instagramAppID)"
```
앱 수준 사용 제한이 걸려있긴 한데, 저희는 스토리 공유 용도로만 사용하기 때문에 큰 문제는 없을 것으로 보입니다.
애니또 대시보드에서 딱히 할 수 있는건 없긴 한데, 참여하고 싶으신 분들은 FacebookID나 사용자 이름 말씀해주시면 대시보드에 개발자 역할로 추가해드리겠습니다. 말씀해주세요.🙇‍♂️
함께 했던 기록 부분에서 테스트해주시면 됩니다.
그 전에 꼭 Key.plist에 instagramAppID를 설정해주세요. AppID는 노션 기밀사항 내부에 적어뒀습니다. …
> [FIX] 인스타그램 공유가 안되는 문제를 해결했습니다.

- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/ViewModel/DetailWaitViewModel.swift
- Manito/ManitoTests/Presentation/DetailWait/ViewModel/DetailWaitViewModelTest.swift
대기방(DetailWait)의 ViewModel의 viewDidLoad란 input을 받아서 만든 viewDidLoad 스트림이 있었습니다.
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/blob/5edb023c022b28c1fe69ce1334a7a4c2f59f9bd4/Manito/Manito/Screens/Detail-Wait/ViewModel/DetailWaitViewModel.swift#L72-L78
위 viewDidLoad 스트림을 사용하는 Output이 위를 포함해서 총 3군데가 있었습니다.
1. `roomInformation Output`
위 코드 그대로 사용
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/blob/5edb023c022b28c1fe69ce1334a7a4c2f59f9bd4/Manito/Manito/Screens/Detail-Wait/ViewModel/DetailWaitViewModel.swift#L133-L134
2. `passedStartDate Output`
viewDidLoad의 방 정보를 가져와 날짜가 지났는지 리턴함
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/blob/5edb023c022b28c1fe69ce1334a7a4c2f59f9bd4/Manito/Manito/Screens/Detail-Wait/ViewModel/DetailWaitViewModel.swift …
> [CHORE] 대기방 방 정보에 대한 Output의 타입을 Result 타입으로 변경했습니다.

- Manito/Manito/Presentation/Scene/ParticipateRoomScene/ViewController/ChooseCharacterViewController.swift
처음에는 방참가 부분에서 케릭터 선택 컬랙션 뷰에서 메모리 릭이 일어나는 줄 알았는데 
어제 듀나랑 얘기하면서 컬랙션 뷰가 아닌 뷰 컨트롤러일 수 도 있겠다 라는 말을 듣고 확인해보니
케릭터 선택 뷰가 있는 ChooseCharacterViewController 에서 메모리 릭이 일어나고 있었습니다. 
문제는 sink 부분에 [weak self] 를 하지 않아서 strong 참조가 되고 있어서 생겼습니다. 
- [weak self] 추가
`feature/581-character-memoryleak-bugfix` 에 오셔서 방참여 후 `IWGE0P` 코드로 진입하여 메모리 릭을 확인해보시면 됩니다. 
| 원래 | 수정 후 |
| ----| --------|
|<img src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/1e1caef4-0845-4065-afb8-76c3e649b191" width="350">         | <img src="https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/59243274/ec5fc7c5-8fe4-44fa-b9e0-03bc27d35fa6" width="350">            |
원래는 ChooseCharacterViewController 도 계속 쌓이고 manittoCollectionView 도 계속 쌓였으나 이젠 잘 해제 됩니다. 
weak self 확인을 잘하자..! 
- close …
> [BUGFIX] ChooseCharacterViewController 가 메모리 릭이 일어나는 부분을 수정했습니다. 

- Manito/Manito.xcodeproj/project.pbxproj
- Manito/Manito/Domain/Error/DetailEdit/DetailEditUsecaseError.swift
- Manito/Manito/Domain/Usecase/DetailWait/DetailEditUsecase.swift
- Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
- Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
- Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
- Manito/Manito/Screens/Detail-Wait/View/DetailEditView.swift
- Manito/Manito/Screens/Detail-Wait/ViewModel/DetailEditViewModel.swift
- Manito/Manito/Screens/Detail-Wait/ViewModel/DetailWaitViewModel.swift
- Manito/Manito/Util/Extension/Combine/UIControl+Combine.swift
- Manito/Manito/Util/Literal/TextLiteral.swift
- Manito/ManitoTests/Domain/Usecase/DetailEditUsecaseTest.swift
대기방 View에 이어 방 정보 수정 View를 이어서 리팩토링 했습니다.
1. 대기방 View 리팩토링
2. UISlider에 대한 Publisher 추가
3. 캘린더 View의 날짜 Subject 값 전달
- 날짜를 선택하고 변경 버튼을 눌렀을때, 시작 날짜가 오늘보다 과거이면 Alert이 뜨게끔 만들었습니다. (이미 캘린더 View에서 UI적으로 막고있음)
- 최대 인원이 현재 참여한 인원보다 많을때, Alert이 뜨게끔 만들었습니다.
ViewModel에서 Input에 방 정보가 이미 오는데도 `var roomDto: CurrentValueSubject<CreatedRoomInfoRequestDTO, Never>` 변수를 사용한 이유가 따로 있습니다. 아래 리뷰 노트에 살짝 적긴 했는데, 노션에 11월 7일 iOS 회의록에 개발중 느꼈던 문제에 대해 적었습니다 참고해주셔요 🙇‍♂️
`feature/586-detailedit-mvvm` 브랜치로 오셔서 테스트를 해볼 순 있지만, 방에 사람이 5명이상 들어와있어야 하기 때문에 불편하실까봐 아래 영상으로 첨부했습니다.
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/assets/78677571/e32d8182-9e7d-48f5-b21a-aef6f83d72f2
이번 리팩토링을 하면서 많이 막혀서 시간이 꽤 걸렸네요... 여러분들께 도움을 요청하려고 노션에 상황을 정리하고 있었는데 적다보니 어? 이렇게 하면 될 것 같은데..? 싶어서 해보니 되길래 무사히 완료했습니다..ㅎㅎ
역시 모르는걸 …
> [REFACTOR] 방 정보 수정 View를 CleanArchitecture + MVVM 구조로 리팩토링 했습니다.
